// Code generated by github.com/xslasd/resgen. DO NOT EDIT.
// This file will be automatically regenerated based on the schema.

package resolver

import (
	"context"
	"embed"
)

var _ embed.FS // 确保 embed 被使用

// Core Engine Definitions
type CodedError interface {
	error
	Code() int
}

// ServerContextBase 包含了底层 Web 框架的通用参数绑定与渲染契约
// 框架适配层（如 GinContext）必须实现此接口。
type ServerContextBase interface {
	// --- 1. 声明式参数绑定 ---
	Path(name string, dest any) error
	Query(name string, dest any) error
	Header(name string, dest any) error

	// Payload 绑定整个请求体（如 JSON 结构体或整个 Form 映射）
	Payload(source BodySource, dest any) error

	// Field 从请求体中提取单个字段（如 Form 中的 key 或上传的文件）
	Field(source BodySource, name string, dest any) error

	// --- 2. 底层响应控制 ---
	// RenderRaw 渲染原始响应（指定 Content-Type 和原始字节，适合文件流等场景）
	RenderRaw(code int, contentType string, body []byte)

	// SetHeader 设置响应头
	SetHeader(name, value string)

	// Context 返回标准的 context.Context
	Context() context.Context

	// RenderJson 以 HTTP 状态码 code 将 obj 序列化后，
	// 以 "application/json" Content-Type 写入响应。
	RenderJson(code int, obj any)

	// RenderText 以 HTTP 状态码 code 将 obj 序列化后，
	// 以 "text/plain" Content-Type 写入响应。
	RenderText(code int, obj any)
}

// ServerContext 接口定义
type ServerContext[T any] interface {
	ServerContextBase
	Native() T
}

// BodySource 定义了请求体绑定的来源/类型
type BodySource string

// HandlerFunc 是 Resgen 处理器的通用签名
type HandlerFunc[C any] func(request C, info MethodInfo)

// EngineRegister 定义将路由挂载到外部框架的钩子
type EngineRegister[C ServerContextBase] func(e *Engine[C], info MethodInfo, handler HandlerFunc[C])

// MethodInfo 接口元数据
type MethodInfo struct {
	Module string
	Group  string
	Method string
	Name   string
	Path   string
}

// Engine 核心 API 引擎
type Engine[C ServerContextBase] struct {
	onRegister EngineRegister[C]

	decorator any
	validator any
	responder any
}

// NewEngine 创建引擎
func NewEngine[C ServerContextBase]() *Engine[C] {
	return &Engine[C]{}
}

func (e *Engine[C]) BindDecorator(d any) *Engine[C] { e.decorator = d; return e }
func (e *Engine[C]) BindValidator(v any) *Engine[C] { e.validator = v; return e }
func (e *Engine[C]) BindResponder(r any) *Engine[C] { e.responder = r; return e }

// BindRegister 挂载路由注册钩子
func (e *Engine[C]) BindRegister(register EngineRegister[C]) *Engine[C] {
	e.onRegister = register

	e.registerApiDocs()

	return e
}

// Getters 供生成的代码使用
func (e *Engine[C]) Decorator() any { return e.decorator }
func (e *Engine[C]) Validator() any { return e.validator }
func (e *Engine[C]) Responder() any { return e.responder }

// Register 注册路由
func (e *Engine[C]) Register(info MethodInfo, handler HandlerFunc[C]) {
	if e.onRegister != nil {
		e.onRegister(e, info, handler)
	}
}

//go:embed docs/api.html
var apiHTML []byte

//go:embed docs/api.json
var apiJSON []byte

func (e *Engine[C]) registerApiDocs() {
	if e.onRegister == nil {
		return
	}

	// 注册 HTML 页面
	e.Register(MethodInfo{Method: "GET", Path: "/docs", Name: "ApiDocsHTML"}, func(ctx C, info MethodInfo) {
		ctx.RenderRaw(200, "text/html; charset=utf-8", apiHTML)
	})

	// 注册 JSON 数据接口
	e.Register(MethodInfo{Method: "GET", Path: "/docs/json", Name: "ApiDocsJSON"}, func(ctx C, info MethodInfo) {
		ctx.RenderRaw(200, "application/json; charset=utf-8", apiJSON)
	})
}

// ==========================================
// 1. Context Definitions
// ==========================================

const (
	SourceText      BodySource = "text"
	SourceJson      BodySource = "json"
	SourceForm      BodySource = "form"
	SourceMultipart BodySource = "multipart"
	SourceXml       BodySource = "xml"
)

// ==========================================
// 2. Decorators & Validators
// ==========================================

// Decorator 定义了可用于 API 端点的装饰器策略契约
type Decorator[T any] interface {
	LoginRequired(ctx T, info MethodInfo) error
}

// Validator [T any] 定义了带有上下文感知的验证逻辑契约
type Validator[T any] interface {
	// Required 校验逻辑
	Required(ctx T, fieldName string, value any) error
	// Email 校验逻辑
	Email(ctx T, fieldName string, value any) error
	// Mobile 校验逻辑
	Mobile(ctx T, fieldName string, value any) error
	// Min 校验逻辑
	Min(ctx T, fieldName string, value any, Len int) error
	// Max 校验逻辑
	Max(ctx T, fieldName string, value any, Len int) error
	// FileRule 校验逻辑
	FileRule(ctx T, fieldName string, value any, MaxSize int, Types []string, Msg string) error
}

// Responder [T any] 定义了响应包装与错误映射契约
type Responder[T any] interface {
	// ErrorToStatus 将错误转换为 HTTP 状态码
	ErrorToStatus(ctx T, err error) int
	// BindResData 将数据和错误绑定到 ResData 包装器中
	BindResData(ctx T, data any, err error) ResData
}

// ==========================================
// 3. Response Wrappers
// ==========================================

// 定义统一响应包装器
// ResData 输出模型
type ResData struct {
	Code int    `json:"code"`
	Msg  string `json:"msg"`
	Data any    `json:"data"`
}
