// Code generated by github.com/xslasd/resgen v0.7.2. DO NOT EDIT.
// This file will be automatically regenerated based on the schema.

package resolver

import (
	"context"

	"github.com/xslasd/resgen/examples/scalars"
)

// ==========================================
// 1. Enums
// ==========================================

// ==========================================
// 2. Models
// ==========================================

// 数据模型
type User struct {
	ID       int    `json:"id"`
	Username string `json:"username"`
	Email    string `json:"email"`
}

// Token 输出模型
type Token struct {
	Token     string `json:"token"`
	ExpiresAt int    `json:"expires_at"`
}

// RegisterInput 输入模型
type RegisterInput struct {
	Username string `json:"username" form:"username"`
	Email    string `json:"email" form:"email"`
	Mobile   string `json:"mobile" form:"mobile"`
	Password string `json:"password" form:"password"`
}

// UpdateInput 输入模型
type UpdateInput struct {
	ID    int     `json:"id"`
	Email *string `json:"email"`
}

// 跨字段校验输入模型：startTime 关联校验 endTime
type TaskPeriodInput struct {
	StartTime scalars.IntTime `json:"start_time"`
	EndTime   scalars.IntTime `json:"end_time"`
}

// LoginArgs 输入模型
type LoginArgs struct {
	Username *string `json:"username"`
	Password *string `json:"password"`
}

// ==========================================
// 2. Resolver Interface
// ==========================================

// AuthDemoResolver 定义模块业务逻辑接口
type AuthDemoResolver[T any] interface {

	// 注册：使用字段级校验器，请求 form 表单
	//
	// POST /auth/register
	Register(ctx context.Context, input *RegisterInput) (*User, error)

	// 跨字段关联校验：校验 startTime 是否早于 endTime
	//
	// POST /auth/period
	SetPeriod(ctx context.Context, input *TaskPeriodInput) (*string, error)

	BindLogin(request ServerContextBase, input *LoginArgs) error
	ValidateLogin(ctx T, input *LoginArgs) error
	// 登录：完全接管绑定与校验逻辑（业务层手动处理）
	//
	// POST /auth/login
	Login(ctx context.Context, input *LoginArgs) (*Token, error)

	// 获取当前用户：全局 loginRequired 装饰器在请求阶段拦截
	//
	// GET /auth/me
	GetMe(ctx context.Context) (*User, error)

	// 特化调用前拦截：仅由当前 Resolver 独立实现（如资源归属校验）
	OnInvoke_CheckOwner_UpdateUser(ctx T, info MethodInfo, input *UpdateInput) error
	// 更新用户：
	// - loginRequired（request 阶段，全局）：验证登录态
	// - checkOwner（invoke 阶段，业务独立）：验证是否为资源拥有者
	// - maskEmail（response 阶段，业务独立）：脱敏邮件地址后再返回
	//
	// POST /auth/update
	UpdateUser(ctx context.Context, input *UpdateInput) (*User, error)
	// 特化响应后处理：仅由当前 Resolver 独立实现（如数据脱敏）
	OnResponse_MaskEmail_UpdateUser(ctx T, info MethodInfo, input *UpdateInput, result *User, err error) (*User, error)

	// 管理员接口：需要特定角色，组合多个全局装饰器
	//
	// DELETE /auth/:id
	DeleteUser(ctx context.Context, id *int) (*string, error)
}

// ==========================================
// 3. Executor / Binders
// ==========================================

/*
Resgen 自动化执行流说明:
1. Request Decorators  : 全局与特化请求拦截 (Auth, RateLimit 等)
2. Binding & Validation: 自动参数绑定与核心规则校验
3. Invoke Decorators   : 业务调用前的特化处理 (OwnerCheck 等)
4. Business Logic      : 调用 Resolver 接口实现的业务逻辑
5. Response Decorators : 结果脱敏或格式转换 (MaskEmail 等)
6. Result Response     : 最终结果渲染响应
*/

func MountAuthDemo[T any, C ServerContext[T]](en *Engine[C], biz AuthDemoResolver[T]) {
	d, _ := en.Decorator().(Decorator[T])
	v, _ := en.Validator().(Validator[T])
	r, _ := en.Responder().(Responder[T])
	executor := &AuthDemoExecutor[T, C]{
		en:  en,
		biz: biz,
		d:   d,
		v:   v,
		r:   r,
	}

	executor.mount()
}

type AuthDemoExecutor[T any, C ServerContext[T]] struct {
	en  *Engine[C]
	biz AuthDemoResolver[T]
	d   Decorator[T]
	v   Validator[T]
	r   Responder[T]
}

func (e *AuthDemoExecutor[T, C]) mount() {

	// --- 注册组: Auth ---

	infoRegister := MethodInfo{
		Module: "AuthDemo",
		Group:  "/auth",
		Method: "POST",
		Name:   "Register",
		Path:   "/auth/register",
	}
	e.register(infoRegister, e.handleRegister)

	infoSetPeriod := MethodInfo{
		Module: "AuthDemo",
		Group:  "/auth",
		Method: "POST",
		Name:   "SetPeriod",
		Path:   "/auth/period",
	}
	e.register(infoSetPeriod, e.handleSetPeriod)

	infoLogin := MethodInfo{
		Module: "AuthDemo",
		Group:  "/auth",
		Method: "POST",
		Name:   "Login",
		Path:   "/auth/login",
	}
	e.register(infoLogin, e.handleLogin)

	infoGetMe := MethodInfo{
		Module: "AuthDemo",
		Group:  "/auth",
		Method: "GET",
		Name:   "GetMe",
		Path:   "/auth/me",
	}
	e.register(infoGetMe, e.handleGetMe)

	infoUpdateUser := MethodInfo{
		Module: "AuthDemo",
		Group:  "/auth",
		Method: "POST",
		Name:   "UpdateUser",
		Path:   "/auth/update",
	}
	e.register(infoUpdateUser, e.handleUpdateUser)

	infoDeleteUser := MethodInfo{
		Module: "AuthDemo",
		Group:  "/auth",
		Method: "DELETE",
		Name:   "DeleteUser",
		Path:   "/auth/:id",
	}
	e.register(infoDeleteUser, e.handleDeleteUser)
}

func (e *AuthDemoExecutor[T, C]) register(info MethodInfo, handler HandlerFunc[C]) {
	info.HandlerPos = GetHandlerJumpPath(e.biz, info.Name)
	e.en.Register(info, handler)
}

// handleRegister 封装了端点的自动化执行流
func (e *AuthDemoExecutor[T, C]) handleRegister(request C, info MethodInfo) {
	native := request.Native()
	var input RegisterInput
	if err := e.bindRegister(request, &input); err != nil {
		request.RenderJson(e.r.ErrorToStatus(native, err), e.r.BindResData(native, nil, err))
		return
	}
	if err := e.validateRegister(native, &input); err != nil {
		request.RenderJson(e.r.ErrorToStatus(native, err), e.r.BindResData(native, nil, err))
		return
	}
	result, err := e.biz.Register(request.Context(), &input)
	if err != nil {
		request.RenderJson(e.r.ErrorToStatus(native, err), e.r.BindResData(native, nil, err))
		return
	}
	request.RenderJson(201, e.r.BindResData(native, result, nil))
}

// bindRegister 自动生成的参数提取与转换实现
func (e *AuthDemoExecutor[T, C]) bindRegister(request C, input *RegisterInput) error {
	if err := request.Payload(SourceForm, input); err != nil {
		return err
	}
	return nil
}

// validateRegister 参数验证逻辑
func (e *AuthDemoExecutor[T, C]) validateRegister(ctx T, input *RegisterInput) error {
	if err := e.v.Required(ctx, "username", input.Username); err != nil {
		return err
	}
	if err := e.v.Min(ctx, "username", input.Username, 3); err != nil {
		return err
	}
	if err := e.v.Max(ctx, "username", input.Username, 20); err != nil {
		return err
	}
	if err := e.v.Required(ctx, "email", input.Email); err != nil {
		return err
	}
	if err := e.v.Email(ctx, "email", input.Email); err != nil {
		return err
	}
	if err := e.v.Required(ctx, "mobile", input.Mobile); err != nil {
		return err
	}
	if err := e.v.Mobile(ctx, "mobile", input.Mobile); err != nil {
		return err
	}
	if err := e.v.Required(ctx, "password", input.Password); err != nil {
		return err
	}
	if err := e.v.Min(ctx, "password", input.Password, 8); err != nil {
		return err
	}

	return nil
}

// handleSetPeriod 封装了端点的自动化执行流
func (e *AuthDemoExecutor[T, C]) handleSetPeriod(request C, info MethodInfo) {
	native := request.Native()
	var input TaskPeriodInput
	if err := e.bindSetPeriod(request, &input); err != nil {
		request.RenderJson(e.r.ErrorToStatus(native, err), e.r.BindResData(native, nil, err))
		return
	}
	if err := e.validateSetPeriod(native, &input); err != nil {
		request.RenderJson(e.r.ErrorToStatus(native, err), e.r.BindResData(native, nil, err))
		return
	}
	result, err := e.biz.SetPeriod(request.Context(), &input)
	if err != nil {
		request.RenderJson(e.r.ErrorToStatus(native, err), e.r.BindResData(native, nil, err))
		return
	}
	request.RenderJson(200, e.r.BindResData(native, result, nil))
}

// bindSetPeriod 自动生成的参数提取与转换实现
func (e *AuthDemoExecutor[T, C]) bindSetPeriod(request C, input *TaskPeriodInput) error {
	if err := request.Payload(SourceJSON, input); err != nil {
		return err
	}
	return nil
}

// validateSetPeriod 参数验证逻辑
func (e *AuthDemoExecutor[T, C]) validateSetPeriod(ctx T, input *TaskPeriodInput) error {
	if err := e.v.Required(ctx, "startTime", input.StartTime); err != nil {
		return err
	}
	if err := e.v.TimeBefore(ctx, "startTime", input.StartTime, input.EndTime); err != nil {
		return err
	}
	if err := e.v.Required(ctx, "endTime", input.EndTime); err != nil {
		return err
	}

	return nil
}

// handleLogin 封装了端点的自动化执行流
func (e *AuthDemoExecutor[T, C]) handleLogin(request C, info MethodInfo) {
	native := request.Native()
	var input LoginArgs
	if err := e.biz.BindLogin(request, &input); err != nil {
		request.RenderJson(e.r.ErrorToStatus(native, err), e.r.BindResData(native, nil, err))
		return
	}
	if err := e.biz.ValidateLogin(native, &input); err != nil {
		request.RenderJson(e.r.ErrorToStatus(native, err), e.r.BindResData(native, nil, err))
		return
	}
	result, err := e.biz.Login(request.Context(), &input)
	if err != nil {
		request.RenderJson(e.r.ErrorToStatus(native, err), e.r.BindResData(native, nil, err))
		return
	}
	request.RenderJson(200, e.r.BindResData(native, result, nil))
}

// handleGetMe 封装了端点的自动化执行流
func (e *AuthDemoExecutor[T, C]) handleGetMe(request C, info MethodInfo) {
	native := request.Native()
	if err := e.d.LoginRequired(native, info); err != nil {
		request.RenderJson(e.r.ErrorToStatus(native, err), e.r.BindResData(native, nil, err))
		return
	}
	result, err := e.biz.GetMe(request.Context())
	if err != nil {
		request.RenderJson(e.r.ErrorToStatus(native, err), e.r.BindResData(native, nil, err))
		return
	}
	request.RenderJson(200, e.r.BindResData(native, result, nil))
}

// handleUpdateUser 封装了端点的自动化执行流
func (e *AuthDemoExecutor[T, C]) handleUpdateUser(request C, info MethodInfo) {
	native := request.Native()
	if err := e.d.LoginRequired(native, info); err != nil {
		request.RenderJson(e.r.ErrorToStatus(native, err), e.r.BindResData(native, nil, err))
		return
	}
	var input UpdateInput
	if err := e.bindUpdateUser(request, &input); err != nil {
		request.RenderJson(e.r.ErrorToStatus(native, err), e.r.BindResData(native, nil, err))
		return
	}
	if err := e.validateUpdateUser(native, &input); err != nil {
		request.RenderJson(e.r.ErrorToStatus(native, err), e.r.BindResData(native, nil, err))
		return
	}
	if err := e.biz.OnInvoke_CheckOwner_UpdateUser(native, info, &input); err != nil {
		request.RenderJson(e.r.ErrorToStatus(native, err), e.r.BindResData(native, nil, err))
		return
	}
	result, err := e.biz.UpdateUser(request.Context(), &input)
	if res, rerr := e.biz.OnResponse_MaskEmail_UpdateUser(native, info, &input, result, err); rerr != nil {
		request.RenderJson(e.r.ErrorToStatus(native, rerr), e.r.BindResData(native, nil, rerr))
		return
	} else {
		result = res
		err = rerr
	}
	if err != nil {
		request.RenderJson(e.r.ErrorToStatus(native, err), e.r.BindResData(native, nil, err))
		return
	}
	request.RenderJson(200, e.r.BindResData(native, result, nil))
}

// bindUpdateUser 自动生成的参数提取与转换实现
func (e *AuthDemoExecutor[T, C]) bindUpdateUser(request C, input *UpdateInput) error {
	if err := request.Payload(SourceJSON, input); err != nil {
		return err
	}
	return nil
}

// validateUpdateUser 参数验证逻辑
func (e *AuthDemoExecutor[T, C]) validateUpdateUser(ctx T, input *UpdateInput) error {
	if err := e.v.Required(ctx, "id", input.ID); err != nil {
		return err
	}
	if input.Email != nil {
		if *input.Email != "" {
			if err := e.v.Email(ctx, "email", *input.Email); err != nil {
				return err
			}
		}
	}

	return nil
}

// handleDeleteUser 封装了端点的自动化执行流
func (e *AuthDemoExecutor[T, C]) handleDeleteUser(request C, info MethodInfo) {
	native := request.Native()
	if err := e.d.Auth(native, info, "admin"); err != nil {
		request.RenderJson(e.r.ErrorToStatus(native, err), e.r.BindResData(native, nil, err))
		return
	}
	if err := e.d.LoginRequired(native, info); err != nil {
		request.RenderJson(e.r.ErrorToStatus(native, err), e.r.BindResData(native, nil, err))
		return
	}
	var IDVal *int

	if val := request.GetPath("id"); val != "" {
		if v, err := IntFromParam(val); err == nil {
			v2 := v
			IDVal = &v2
		} else {
			request.RenderJson(e.r.ErrorToStatus(native, err), e.r.BindResData(native, nil, err))
			return
		}
	}
	result, err := e.biz.DeleteUser(request.Context(), IDVal)
	if err != nil {
		request.RenderJson(e.r.ErrorToStatus(native, err), e.r.BindResData(native, nil, err))
		return
	}
	request.RenderJson(200, e.r.BindResData(native, result, nil))
}
