// Code generated by github.com/xslasd/resgen. DO NOT EDIT.
// This file will be automatically regenerated based on the schema.

package resolver

import (
	"context"
)

// ==========================================
// 1. Models
// ==========================================

// Report 输出模型
type Report struct {
	Title   string `json:"title"`
	Summary string `json:"summary"`
}

// JsonInput 输入模型
type JsonInput struct {
	Title   string `json:"title"`
	Content string `json:"content"`
}

// FormInput 输入模型
type FormInput struct {
	Name  string `json:"name"`
	Email string `json:"email"`
}

// ==========================================
// 2. Resolver Interface
// ==========================================

// ContentTypeDemoResolver 定义模块业务逻辑接口
type ContentTypeDemoResolver[T any] interface {

	// SubmitJson POST /content/json
	SubmitJson(ctx context.Context, input *JsonInput) (*string, error)

	// SubmitForm POST /content/form
	SubmitForm(ctx context.Context, input *FormInput) (*string, error)

	// SubmitMultipart POST /content/multipart
	SubmitMultipart(ctx context.Context, title string) (*string, error)

	// ExportText GET /export/text
	ExportText(ctx context.Context) (*string, error)

	// ExportJson GET /export/json
	ExportJson(ctx context.Context) (*Report, error)

	// ExportXml GET /export/xml
	ExportXml(ctx context.Context) (*Report, error)
}

// ==========================================
// 3. Executor / Binders
// ==========================================

/*
Resgen 自动化执行流说明:
1. Request Decorators  : 全局与特化请求拦截 (Auth, RateLimit 等)
2. Binding & Validation: 自动参数绑定与核心规则校验
3. Invoke Decorators   : 业务调用前的特化处理 (OwnerCheck 等)
4. Business Logic      : 调用 Resolver 接口实现的业务逻辑
5. Response Decorators : 结果脱敏或格式转换 (MaskEmail 等)
6. Result Response     : 最终结果渲染响应
*/

func MountContentTypeDemo[T any, C ServerContext[T]](en *Engine[C], biz ContentTypeDemoResolver[T]) {
	d, _ := en.Decorator().(Decorator[T])
	v, _ := en.Validator().(Validator[T])
	r, _ := en.Responder().(Responder[T])
	executor := &ContentTypeDemoExecutor[T, C]{
		en:  en,
		biz: biz,
		d:   d,
		v:   v,
		r:   r,
	}

	executor.mount()
}

type ContentTypeDemoExecutor[T any, C ServerContext[T]] struct {
	en  *Engine[C]
	biz ContentTypeDemoResolver[T]
	d   Decorator[T]
	v   Validator[T]
	r   Responder[T]
}

func (e *ContentTypeDemoExecutor[T, C]) mount() {

	// --- 注册组: Content ---

	infoSubmitJson := MethodInfo{
		Module: "ContentTypeDemo",
		Group:  "/content",
		Method: "POST",
		Name:   "SubmitJson",
		Path:   "/content/json",
	}
	e.en.Register(infoSubmitJson, e.handleSubmitJson)

	infoSubmitForm := MethodInfo{
		Module: "ContentTypeDemo",
		Group:  "/content",
		Method: "POST",
		Name:   "SubmitForm",
		Path:   "/content/form",
	}
	e.en.Register(infoSubmitForm, e.handleSubmitForm)

	infoSubmitMultipart := MethodInfo{
		Module: "ContentTypeDemo",
		Group:  "/content",
		Method: "POST",
		Name:   "SubmitMultipart",
		Path:   "/content/multipart",
	}
	e.en.Register(infoSubmitMultipart, e.handleSubmitMultipart)

	// --- 注册组: Export ---

	infoExportText := MethodInfo{
		Module: "ContentTypeDemo",
		Group:  "/export",
		Method: "GET",
		Name:   "ExportText",
		Path:   "/export/text",
	}
	e.en.Register(infoExportText, e.handleExportText)

	infoExportJson := MethodInfo{
		Module: "ContentTypeDemo",
		Group:  "/export",
		Method: "GET",
		Name:   "ExportJson",
		Path:   "/export/json",
	}
	e.en.Register(infoExportJson, e.handleExportJson)

	infoExportXml := MethodInfo{
		Module: "ContentTypeDemo",
		Group:  "/export",
		Method: "GET",
		Name:   "ExportXml",
		Path:   "/export/xml",
	}
	e.en.Register(infoExportXml, e.handleExportXml)
}

// handleSubmitJson 封装了端点的自动化执行流
func (e *ContentTypeDemoExecutor[T, C]) handleSubmitJson(request C, info MethodInfo) {
	native := request.Native()
	var input JsonInput
	if err := e.bindSubmitJson(request, &input); err != nil {
		request.RenderJson(e.r.ErrorToStatus(native, err), e.r.BindResData(native, nil, err))
		return
	}
	if err := e.validateSubmitJson(native, &input); err != nil {
		request.RenderJson(e.r.ErrorToStatus(native, err), e.r.BindResData(native, nil, err))
		return
	}
	result, err := e.biz.SubmitJson(request.Context(), &input)
	if err != nil {
		request.RenderJson(e.r.ErrorToStatus(native, err), e.r.BindResData(native, nil, err))
		return
	}
	request.RenderJson(200, e.r.BindResData(native, result, nil))
}

// bindSubmitJson 自动生成的参数提取与转换实现
func (e *ContentTypeDemoExecutor[T, C]) bindSubmitJson(request C, input *JsonInput) error {
	if err := request.Payload(SourceJson, input); err != nil {
		return err
	}
	return nil
}

// validateSubmitJson 参数验证逻辑
func (e *ContentTypeDemoExecutor[T, C]) validateSubmitJson(ctx T, input *JsonInput) error {
	// Pass 1: Required validations
	if err := e.v.Required(ctx, "title", input.Title); err != nil {
		return err
	}
	if err := e.v.Required(ctx, "content", input.Content); err != nil {
		return err
	}

	// Pass 2: Other validations
	return nil
}

// handleSubmitForm 封装了端点的自动化执行流
func (e *ContentTypeDemoExecutor[T, C]) handleSubmitForm(request C, info MethodInfo) {
	native := request.Native()
	var input FormInput
	if err := e.bindSubmitForm(request, &input); err != nil {
		request.RenderJson(e.r.ErrorToStatus(native, err), e.r.BindResData(native, nil, err))
		return
	}
	if err := e.validateSubmitForm(native, &input); err != nil {
		request.RenderJson(e.r.ErrorToStatus(native, err), e.r.BindResData(native, nil, err))
		return
	}
	result, err := e.biz.SubmitForm(request.Context(), &input)
	if err != nil {
		request.RenderJson(e.r.ErrorToStatus(native, err), e.r.BindResData(native, nil, err))
		return
	}
	request.RenderJson(200, e.r.BindResData(native, result, nil))
}

// bindSubmitForm 自动生成的参数提取与转换实现
func (e *ContentTypeDemoExecutor[T, C]) bindSubmitForm(request C, input *FormInput) error {
	if err := request.Payload(SourceForm, input); err != nil {
		return err
	}
	return nil
}

// validateSubmitForm 参数验证逻辑
func (e *ContentTypeDemoExecutor[T, C]) validateSubmitForm(ctx T, input *FormInput) error {
	// Pass 1: Required validations
	if err := e.v.Required(ctx, "name", input.Name); err != nil {
		return err
	}
	if err := e.v.Required(ctx, "email", input.Email); err != nil {
		return err
	}

	// Pass 2: Other validations
	return nil
}

// handleSubmitMultipart 封装了端点的自动化执行流
func (e *ContentTypeDemoExecutor[T, C]) handleSubmitMultipart(request C, info MethodInfo) {
	native := request.Native()
	var titleVal string

	if val := request.GetQuery("title"); val != "" {
		titleVal = val
	}
	result, err := e.biz.SubmitMultipart(request.Context(), titleVal)
	if err != nil {
		request.RenderJson(e.r.ErrorToStatus(native, err), e.r.BindResData(native, nil, err))
		return
	}
	request.RenderJson(200, e.r.BindResData(native, result, nil))
}

// handleExportText 封装了端点的自动化执行流
func (e *ContentTypeDemoExecutor[T, C]) handleExportText(request C, info MethodInfo) {
	native := request.Native()
	result, err := e.biz.ExportText(request.Context())
	if err != nil {
		request.RenderJson(e.r.ErrorToStatus(native, err), e.r.BindResData(native, nil, err))
		return
	}
	request.RenderText(200, result)
}

// handleExportJson 封装了端点的自动化执行流
func (e *ContentTypeDemoExecutor[T, C]) handleExportJson(request C, info MethodInfo) {
	native := request.Native()
	result, err := e.biz.ExportJson(request.Context())
	if err != nil {
		request.RenderJson(e.r.ErrorToStatus(native, err), e.r.BindResData(native, nil, err))
		return
	}
	request.RenderJson(200, result)
}

// handleExportXml 封装了端点的自动化执行流
func (e *ContentTypeDemoExecutor[T, C]) handleExportXml(request C, info MethodInfo) {
	native := request.Native()
	result, err := e.biz.ExportXml(request.Context())
	if err != nil {
		request.RenderJson(e.r.ErrorToStatus(native, err), e.r.BindResData(native, nil, err))
		return
	}
	request.RenderXml(200, result)
}
