// Code generated by github.com/xslasd/resgen v0.7.2. DO NOT EDIT.
// This file will be automatically regenerated based on the schema.

package resolver

import (
	"context"
	"embed"
	"encoding/json"
	"fmt"
	"path/filepath"
	"reflect"
	"runtime"
	"strconv"

	"github.com/mitchellh/mapstructure"
)

var _ embed.FS // 确保 embed 被使用

// LocalFileDownload 专门用于封装本地文件下载的信息
// 当在 DSL 中将返回类型设为 File 时，底层的业务方法统一返回此载体
type LocalFileDownload struct {
	FilePath    string // 本地物理文件路径
	Filename    string // 客户端下载时的文件名
	ContentType string // 文件 MIME 类型。若 DSL 中已声明已知格式 (如 ctype=pdf)，留空即可由执行器强行注入契约 MIME
}

// Core Engine Definitions
type CodedError interface {
	error
	Code() int
}

// ServerContextBase 包含了底层 Web 框架的通用参数绑定与渲染契约
// 框架适配层（如 GinContext）必须实现此接口。
type ServerContextBase interface {
	// --- 1.1 获取原始字符串 (用于 Scalar 和基础类型内置解析) ---
	GetPath(name string) string
	GetQuery(name string) string
	GetHeader(name string) string

	// Payload 绑定整个请求体（如 JSON 结构体或整个 Form 映射）
	Payload(source BodySource, dest any) error

	// --- 2. 底层响应控制 ---
	// RenderRaw 渲染原始响应（指定 Content-Type 和原始字节，适合文件流等场景）
	RenderRaw(code int, contentType string, body []byte)

	// Context 返回标准的 context.Context
	Context() context.Context

	// RenderJson 以 HTTP 状态码 code 将 obj 序列化后，
	// 以 "application/json" Content-Type 写入响应。
	RenderJson(code int, obj any)

	// RenderText 以 HTTP 状态码 code 将 obj 序列化后，
	// 以 "text/plain" Content-Type 写入响应。
	RenderText(code int, obj any)

	// RenderXml 以 HTTP 状态码 code 将 obj 序列化后，
	// 以 "application/xml" Content-Type 写入响应。
	RenderXml(code int, obj any)

	// RenderStream 以 HTTP 状态码 code 将 localFileDownload 写入流式响应。
	RenderStream(code int, localFileDownload LocalFileDownload)
}

// ServerContext 接口定义
type ServerContext[T any] interface {
	ServerContextBase
	Native() T
}

// BodySource 定义了请求体绑定的来源/类型
type BodySource string

// HandlerFunc 是 Resgen 处理器的通用签名
type HandlerFunc[C any] func(request C, info MethodInfo)

// EngineRegister 定义将路由挂载到外部框架的钩子
type EngineRegister[C ServerContextBase] func(e *Engine[C], info MethodInfo, handler HandlerFunc[C])

// MethodInfo 接口元数据
type MethodInfo struct {
	Module     string
	Group      string
	Method     string
	Name       string
	Path       string
	HandlerPos string // 新增：可一键在控制台点击跳转的物理处理器路径
}

// Engine 核心 API 引擎
type Engine[C ServerContextBase] struct {
	onRegister EngineRegister[C]

	decorator any
	validator any
	responder any
}

// NewEngine 创建引擎
func NewEngine[C ServerContextBase]() *Engine[C] {
	return &Engine[C]{}
}

func (e *Engine[C]) BindDecorator(d any) *Engine[C] { e.decorator = d; return e }
func (e *Engine[C]) BindValidator(v any) *Engine[C] { e.validator = v; return e }
func (e *Engine[C]) BindResponder(r any) *Engine[C] { e.responder = r; return e }

// BindRegister 挂载路由注册钩子
func (e *Engine[C]) BindRegister(register EngineRegister[C]) *Engine[C] {
	e.onRegister = register

	e.registerApiDocs()

	return e
}

// Getters 供生成的代码使用
func (e *Engine[C]) Decorator() any { return e.decorator }
func (e *Engine[C]) Validator() any { return e.validator }
func (e *Engine[C]) Responder() any { return e.responder }

// Register 注册路由
func (e *Engine[C]) Register(info MethodInfo, handler HandlerFunc[C]) {
	if e.onRegister != nil {
		e.onRegister(e, info, handler)
	}
}

// GetHandlerJumpPath 通过反射与运行期PC指针定位真实的业务函数源文件物理位置和行号，实现100%精准的定义行号跳转
func GetHandlerJumpPath(biz any, methodName string) string {
	if biz == nil {
		return ""
	}
	// 通过 Type 获取方法，它的 Func.Pointer() 是真实的原始函数入口，不会落入反射蹦床
	t := reflect.TypeOf(biz)
	method, ok := t.MethodByName(methodName)
	if !ok {
		return ""
	}

	pc := method.Func.Pointer()
	fn := runtime.FuncForPC(pc)
	if fn == nil {
		return ""
	}

	file, line := fn.FileLine(pc)

	// 全自动计算项目在编译时的基目录，从而把绝对路径智能修剪为工作区相对路径
	_, thisFile, _, _ := runtime.Caller(0)
	rootDir := filepath.Dir(filepath.Dir(filepath.Dir(filepath.ToSlash(thisFile))))
	if relPath, err := filepath.Rel(rootDir, file); err == nil {
		file = relPath
	}

	// 标准化路径并返回绝对精确的项目相对路径与定义行号，支持 IDE 控制台 Ctrl+点击 一键直达函数定义处
	return fmt.Sprintf("%s:%d (%s)", filepath.ToSlash(file), line, methodName)
}

//go:embed docs/api.html
var apiHTML []byte

//go:embed docs/api.json
var apiJSON []byte

func (e *Engine[C]) registerApiDocs() {
	if e.onRegister == nil {
		return
	}

	_, thisFile, line, _ := runtime.Caller(0)
	rootDir := filepath.Dir(filepath.Dir(filepath.Dir(filepath.ToSlash(thisFile))))
	if relPath, err := filepath.Rel(rootDir, thisFile); err == nil {
		thisFile = relPath
	}
	filePos := filepath.ToSlash(thisFile)

	// 注册 HTML 页面
	e.Register(MethodInfo{
		Method:     "GET",
		Path:       "/docs",
		Name:       "ApiDocsHTML",
		HandlerPos: fmt.Sprintf("%s:%d (ApiDocsHTML)", filePos, line+11),
	}, func(ctx C, info MethodInfo) {
		ctx.RenderRaw(200, "text/html; charset=utf-8", apiHTML)
	})

	// 注册 JSON 数据接口
	e.Register(MethodInfo{
		Method:     "GET",
		Path:       "/docs/json",
		Name:       "ApiDocsJSON",
		HandlerPos: fmt.Sprintf("%s:%d (ApiDocsJSON)", filePos, line+18),
	}, func(ctx C, info MethodInfo) {
		ctx.RenderRaw(200, "application/json; charset=utf-8", apiJSON)
	})
}

// ==========================================
// 1. Context Definitions
// ==========================================

const (
	SourceForm      BodySource = "form"
	SourceHTML      BodySource = "html"
	SourceJSON      BodySource = "json"
	SourceMultipart BodySource = "multipart"
	SourceText      BodySource = "text"
	SourceToml      BodySource = "toml"
	SourceXML       BodySource = "xml"
	SourceYaml      BodySource = "yaml"
)

// --- 基础类型内置解析辅助函数 ---

func IntFromParam(s string) (int, error) {
	return strconv.Atoi(s)
}

func Int64FromParam(s string) (int64, error) {
	return strconv.ParseInt(s, 10, 64)
}

func FloatFromParam(s string) (float64, error) {
	return strconv.ParseFloat(s, 64)
}

func BoolFromParam(s string) (bool, error) {
	return strconv.ParseBool(s)
}

// AnyFromParam 作为一个通用的逃生舱，返回原始字符串
func AnyFromParam(s string) (any, error) {
	return s, nil
}

// StringifyUnionDiscriminator 是一个内部辅助函数，用于将多态判别器（如 int, string 及它们的指针）安全地格式化为字符串
func StringifyUnionDiscriminator(v any) string {
	if v == nil {
		return ""
	}
	val := reflect.ValueOf(v)
	for val.Kind() == reflect.Ptr {
		if val.IsNil() {
			return ""
		}
		val = val.Elem()
	}
	return fmt.Sprintf("%v", val.Interface())
}

// InvalidEnumError 定义了枚举自检与解析失败时的结构化错误，携带元数据以友好支持多语言(i18n)及统一错误映射
type InvalidEnumError struct {
	FieldName string
	EnumType  string
	Value     any
}

func (e *InvalidEnumError) Error() string {
	if e.FieldName != "" {
		return fmt.Sprintf("invalid %s for field '%s': %v", e.EnumType, e.FieldName, e.Value)
	}
	return fmt.Sprintf("invalid %s value: %v", e.EnumType, e.Value)
}

// ==========================================
// 2. Decorators & Validators
// ==========================================

// Decorator 定义了可用于 API 端点的装饰器策略契约
type Decorator[T any] interface {
	Auth(ctx T, info MethodInfo, Role string) error
	LoginRequired(ctx T, info MethodInfo) error
}

// Validator [T any] 定义了带有上下文感知的验证逻辑契约
type Validator[T any] interface {
	// Required 校验逻辑
	Required(ctx T, fieldName string, value any) error
	// Email 校验逻辑
	Email(ctx T, fieldName string, value any) error
	// Mobile 校验逻辑
	Mobile(ctx T, fieldName string, value any) error
	// Min 校验逻辑
	Min(ctx T, fieldName string, value any, Len int) error
	// Max 校验逻辑
	Max(ctx T, fieldName string, value any, Len int) error
	// TimeBefore 校验逻辑
	TimeBefore(ctx T, fieldName string, value any, TargetField any) error
	// FileRule 校验逻辑
	FileRule(ctx T, fieldName string, value any, MaxSize int, Types []string, Msg string) error

	// EnumError 处理枚举校验失败的翻译与包装回调
	EnumError(ctx T, fieldName string, enumType string, value any) error
}

// Responder [T any] 定义了响应包装与错误映射契约
type Responder[T any] interface {
	// ErrorToStatus 将错误转换为 HTTP 状态码
	ErrorToStatus(ctx T, err error) int
	// BindResData 将数据和错误绑定到 ResData 包装器中
	BindResData(ctx T, data any, err error) ResData
	// BindListRes 将数据和错误绑定到 ListRes 包装器中
	BindListRes(ctx T, data any, err error) ListRes
	// BindTreeRes 将数据和错误绑定到 TreeRes 包装器中
	BindTreeRes(ctx T, data any, err error) TreeRes
	// BindPageData 将数据和错误绑定到 PageData 包装器中
	BindPageData(ctx T, data any, err error) PageData
}

// Any 任意类型（逃生舱）
type Any any

// 1. 通用 JSON 响应包装器
type ResData struct {
	Code int    `json:"code" xml:"code"`
	Msg  string `json:"msg" xml:"msg"`
	Data any    `json:"data" xml:"data"`
}

// 3. 通用列表/分页响应包装器
type ListRes struct {
	// 列表数据
	Rows []any `json:"rows"`
	// 总条数
	Total int `json:"total"`
}

// 4. 通用树形结构响应包装器
type TreeRes struct {
	// 顶层树节点列表
	Items []any `json:"items"`
	// 树节点总数
	Total int `json:"total"`
}

// 分页专用包装器
type PageData struct {
	List  any `json:"list"`
	Total int `json:"total"`
	Page  int `json:"page"`
}

// ==========================================
// 3. Union / Polymorphism Resolvers
// ==========================================

// decodeUnionPayload 自适应将 string / []byte / map[string]any / struct 等反序列化到目标结构体 dst
func decodeUnionPayload(rawData any, dst any) error {
	if rawData == nil {
		return nil
	}
	switch v := rawData.(type) {
	case string:
		return json.Unmarshal([]byte(v), dst)
	case []byte:
		return json.Unmarshal(v, dst)
	case map[string]any:
		b, err := json.Marshal(v)
		if err != nil {
			return err
		}
		return json.Unmarshal(b, dst)
	default:
		config := &mapstructure.DecoderConfig{
			TagName: "json",
			Result:  dst,
		}
		decoder, err := mapstructure.NewDecoder(config)
		if err != nil {
			return err
		}
		return decoder.Decode(rawData)
	}
}

func ResolveContentPayload(disc any, rawData any) (any, error) {
	discStr := StringifyUnionDiscriminator(disc)
	switch discStr {
	case "article":
		var dst UnionArticle
		if err := decodeUnionPayload(rawData, &dst); err != nil {
			return nil, err
		}
		return &dst, nil
	case "video":
		var dst UnionVideo
		if err := decodeUnionPayload(rawData, &dst); err != nil {
			return nil, err
		}
		return &dst, nil
	default:
		return rawData, nil
	}
}
