// Code generated by github.com/xslasd/resgen v0.7.0. DO NOT EDIT.
// This file will be automatically regenerated based on the schema.

package resolver

import (
	"context"
)

// ==========================================
// 1. Enums
// ==========================================

// UserRole 1. 基础 String 类型枚举
type UserRole string

const (
	UserRole_ADMIN UserRole = "admin"

	UserRole_USER UserRole = "user"

	UserRole_GUEST UserRole = "guest"
)

// IsValid 检查枚举值是否合法
func (e UserRole) IsValid() bool {
	switch e {
	case UserRole_ADMIN, UserRole_USER, UserRole_GUEST:
		return true
	}
	return false
}

// FromParam 从字符串解析枚举 (用于 Query/Path/Header 参数)
func (e *UserRole) FromParam(ctx any, s string) error {
	switch s {
	case "admin":
		*e = UserRole_ADMIN
		return nil
	case "user":
		*e = UserRole_USER
		return nil
	case "guest":
		*e = UserRole_GUEST
		return nil
	}
	return &InvalidEnumError{
		EnumType: "UserRole",
		Value:    s,
	}
}

// RecordStatus 2. 基础 Int 类型枚举
type RecordStatus int64

const (
	// DISABLE 禁用状态
	RecordStatus_DISABLE RecordStatus = 0
	// ENABLE 启用状态
	RecordStatus_ENABLE RecordStatus = 1
)

// IsValid 检查枚举值是否合法
func (e RecordStatus) IsValid() bool {
	switch e {
	case RecordStatus_DISABLE, RecordStatus_ENABLE:
		return true
	}
	return false
}

// FromParam 从字符串解析枚举 (用于 Query/Path/Header 参数)
func (e *RecordStatus) FromParam(ctx any, s string) error {
	switch s {
	case "0":
		*e = RecordStatus_DISABLE
		return nil
	case "1":
		*e = RecordStatus_ENABLE
		return nil
	}
	return &InvalidEnumError{
		EnumType: "RecordStatus",
		Value:    s,
	}
}

// SpecialTime 由于 Timestamp 退化为了 int64，系统会自动将这个枚举映射为 int64
type SpecialTime int64

const (
	SpecialTime_EPOCH SpecialTime = 0

	SpecialTime_Y2K SpecialTime = 946684800
)

// IsValid 检查枚举值是否合法
func (e SpecialTime) IsValid() bool {
	switch e {
	case SpecialTime_EPOCH, SpecialTime_Y2K:
		return true
	}
	return false
}

// FromParam 从字符串解析枚举 (用于 Query/Path/Header 参数)
func (e *SpecialTime) FromParam(ctx any, s string) error {
	switch s {
	case "0":
		*e = SpecialTime_EPOCH
		return nil
	case "946684800":
		*e = SpecialTime_Y2K
		return nil
	}
	return &InvalidEnumError{
		EnumType: "SpecialTime",
		Value:    s,
	}
}

// ==========================================
// 2. Models
// ==========================================

// UserWithRole 输出模型
type UserWithRole struct {
	Id        *string       `json:"id"`
	Role      *UserRole     `json:"role"`
	Status    *RecordStatus `json:"status"`
	CreatedAt *SpecialTime  `json:"created_at"`
}

// CreateUserInput 输入模型
type CreateUserInput struct {
	Role      UserRole     `json:"role"`
	Status    RecordStatus `json:"status"`
	CreatedAt *SpecialTime `json:"created_at"`
}

// ListResArticle 输出模型
type ListResArticle struct {
	Rows  []Article `json:"rows"`
	Total int       `json:"total"`
}

// TreeResCategoryTreeNode 输出模型
type TreeResCategoryTreeNode struct {
	Items []CategoryTreeNode `json:"items"`
	Total int                `json:"total"`
}

// QueryByRoleArgs 输入模型
type QueryByRoleArgs struct {
	Role   *UserRole     `json:"role"`
	Status *RecordStatus `json:"status"`
}

// ==========================================
// 2. Resolver Interface
// ==========================================

// EnumDemoResolver 定义模块业务逻辑接口
type EnumDemoResolver[T any] interface {

	// CreateUser POST /enum/create
	CreateUser(ctx context.Context, input *CreateUserInput) (*UserWithRole, error)

	// QueryByRole GET /enum/query
	QueryByRole(ctx context.Context, input *QueryByRoleArgs) (*UserWithRole, error)
}

// ==========================================
// 3. Executor / Binders
// ==========================================

/*
Resgen 自动化执行流说明:
1. Request Decorators  : 全局与特化请求拦截 (Auth, RateLimit 等)
2. Binding & Validation: 自动参数绑定与核心规则校验
3. Invoke Decorators   : 业务调用前的特化处理 (OwnerCheck 等)
4. Business Logic      : 调用 Resolver 接口实现的业务逻辑
5. Response Decorators : 结果脱敏或格式转换 (MaskEmail 等)
6. Result Response     : 最终结果渲染响应
*/

func MountEnumDemo[T any, C ServerContext[T]](en *Engine[C], biz EnumDemoResolver[T]) {
	d, _ := en.Decorator().(Decorator[T])
	v, _ := en.Validator().(Validator[T])
	r, _ := en.Responder().(Responder[T])
	executor := &EnumDemoExecutor[T, C]{
		en:  en,
		biz: biz,
		d:   d,
		v:   v,
		r:   r,
	}

	executor.mount()
}

type EnumDemoExecutor[T any, C ServerContext[T]] struct {
	en  *Engine[C]
	biz EnumDemoResolver[T]
	d   Decorator[T]
	v   Validator[T]
	r   Responder[T]
}

func (e *EnumDemoExecutor[T, C]) mount() {

	// --- 注册组: EnumGroup ---

	infoCreateUser := MethodInfo{
		Module: "EnumDemo",
		Group:  "/enum",
		Method: "POST",
		Name:   "CreateUser",
		Path:   "/enum/create",
	}
	e.register(infoCreateUser, e.handleCreateUser)

	infoQueryByRole := MethodInfo{
		Module: "EnumDemo",
		Group:  "/enum",
		Method: "GET",
		Name:   "QueryByRole",
		Path:   "/enum/query",
	}
	e.register(infoQueryByRole, e.handleQueryByRole)
}

func (e *EnumDemoExecutor[T, C]) register(info MethodInfo, handler HandlerFunc[C]) {
	info.HandlerPos = GetHandlerJumpPath(e.biz, info.Name)
	e.en.Register(info, handler)
}

// handleCreateUser 封装了端点的自动化执行流
func (e *EnumDemoExecutor[T, C]) handleCreateUser(request C, info MethodInfo) {
	native := request.Native()
	var input CreateUserInput
	if err := e.bindCreateUser(request, &input); err != nil {
		request.RenderJson(e.r.ErrorToStatus(native, err), e.r.BindResData(native, nil, err))
		return
	}
	if err := e.validateCreateUser(native, &input); err != nil {
		request.RenderJson(e.r.ErrorToStatus(native, err), e.r.BindResData(native, nil, err))
		return
	}
	result, err := e.biz.CreateUser(request.Context(), &input)
	if err != nil {
		request.RenderJson(e.r.ErrorToStatus(native, err), e.r.BindResData(native, nil, err))
		return
	}
	request.RenderJson(200, e.r.BindResData(native, result, nil))
}

// bindCreateUser 自动生成的参数提取与转换实现
func (e *EnumDemoExecutor[T, C]) bindCreateUser(request C, input *CreateUserInput) error {
	if err := request.Payload(SourceJson, input); err != nil {
		return err
	}
	return nil
}

// validateCreateUser 参数验证逻辑
func (e *EnumDemoExecutor[T, C]) validateCreateUser(ctx T, input *CreateUserInput) error {
	if err := e.v.Required(ctx, "role", input.Role); err != nil {
		return err
	}
	if !(input.Role).IsValid() {
		return e.v.EnumError(ctx, "role", "UserRole", input.Role)
	}
	if err := e.v.Required(ctx, "status", input.Status); err != nil {
		return err
	}
	if !(input.Status).IsValid() {
		return e.v.EnumError(ctx, "status", "RecordStatus", input.Status)
	}
	if input.CreatedAt != nil {
		if !(*input.CreatedAt).IsValid() {
			return e.v.EnumError(ctx, "createdAt", "SpecialTime", *input.CreatedAt)
		}
	}

	return nil
}

// handleQueryByRole 封装了端点的自动化执行流
func (e *EnumDemoExecutor[T, C]) handleQueryByRole(request C, info MethodInfo) {
	native := request.Native()
	var input QueryByRoleArgs
	if err := e.bindQueryByRole(request, &input); err != nil {
		request.RenderJson(e.r.ErrorToStatus(native, err), e.r.BindResData(native, nil, err))
		return
	}
	if err := e.validateQueryByRole(native, &input); err != nil {
		request.RenderJson(e.r.ErrorToStatus(native, err), e.r.BindResData(native, nil, err))
		return
	}
	result, err := e.biz.QueryByRole(request.Context(), &input)
	if err != nil {
		request.RenderJson(e.r.ErrorToStatus(native, err), e.r.BindResData(native, nil, err))
		return
	}
	request.RenderJson(200, e.r.BindResData(native, result, nil))
}

// bindQueryByRole 自动生成的参数提取与转换实现
func (e *EnumDemoExecutor[T, C]) bindQueryByRole(request C, input *QueryByRoleArgs) error {
	if val := request.GetQuery("role"); val != "" {
		var tmp UserRole
		if err := tmp.FromParam(request.Native(), val); err != nil {
			return e.v.EnumError(request.Native(), "role", "UserRole", val)
		}
		targetVal := UserRole(tmp)
		input.Role = &targetVal
	}
	if val := request.GetQuery("status"); val != "" {
		var tmp RecordStatus
		if err := tmp.FromParam(request.Native(), val); err != nil {
			return e.v.EnumError(request.Native(), "status", "RecordStatus", val)
		}
		targetVal := RecordStatus(tmp)
		input.Status = &targetVal
	}
	return nil
}

// validateQueryByRole 参数验证逻辑
func (e *EnumDemoExecutor[T, C]) validateQueryByRole(ctx T, input *QueryByRoleArgs) error {
	if input.Role != nil {
		if !(*input.Role).IsValid() {
			return e.v.EnumError(ctx, "role", "UserRole", *input.Role)
		}
	}
	if input.Status != nil {
		if !(*input.Status).IsValid() {
			return e.v.EnumError(ctx, "status", "RecordStatus", *input.Status)
		}
	}

	return nil
}
