// Code generated by github.com/xslasd/resgen v0.7.3. DO NOT EDIT.
// This file will be automatically regenerated based on the schema.

package resolver

import (
	"context"
	"mime/multipart"
)

// ==========================================
// 1. Enums
// ==========================================

// ==========================================
// 2. Models
// ==========================================

// 单文件上传的输入模型
type UploadAvatarInput struct {
	UserId int `json:"user_id" form:"user_id"`
	// 仅允许 JPG/PNG，最大 2MB（2097152 字节）
	Avatar *multipart.FileHeader `json:"avatar" form:"avatar"`
}

// 混合表单：同时包含普通字段与文件
type UploadDocumentInput struct {
	Title       string  `json:"title" form:"title"`
	Description *string `json:"description" form:"description"`
	// 仅允许 PDF，最大 10MB
	Document *multipart.FileHeader `json:"document" form:"document"`
	// 可选封面图片
	Cover *multipart.FileHeader `json:"cover" form:"cover"`
}

// 上传结果模型
type UploadResult struct {
	FileUrl  string `json:"file_url"`
	FileSize int    `json:"file_size"`
	MimeType string `json:"mime_type"`
}

// ==========================================
// 2. Resolver Interface
// ==========================================

// FileDemoResolver 定义模块业务逻辑接口
type FileDemoResolver[T any] interface {

	// 单文件上传：头像
	//
	// POST /files/avatar
	UploadAvatar(ctx context.Context, input *UploadAvatarInput) (*UploadResult, error)

	// 混合表单上传：文档 + 封面
	//
	// POST /files/document
	UploadDocument(ctx context.Context, input *UploadDocumentInput) (*UploadResult, error)

	// 文件下载：成功响应为 PDF 裸流 (wrap=none)，文档精准显示 application/pdf，失败退化为 JSON (etype=json)
	//
	// GET /files/download/:id
	DownloadFile(ctx context.Context, id *int) (*LocalFileDownload, error)

	// 导出 CSV：成功响应为 CSV 裸流 (wrap=none)，文档精准显示 text/csv，失败退化为 JSON (etype=json)
	//
	// GET /files/export/csv
	ExportCsv(ctx context.Context, ids *string) (*LocalFileDownload, error)

	// 动态流下载：通用动态流，业务动态指定 ContentType，失败退化为 JSON (etype=json)
	//
	// GET /files/dynamic/:id
	DownloadDynamic(ctx context.Context, id *int) (*LocalFileDownload, error)
}

// ==========================================
// 3. Executor / Binders
// ==========================================

/*
Resgen 自动化执行流说明:
1. Request Decorators  : 全局与特化请求拦截 (Auth, RateLimit 等)
2. Binding & Validation: 自动参数绑定与核心规则校验
3. Invoke Decorators   : 业务调用前的特化处理 (OwnerCheck 等)
4. Business Logic      : 调用 Resolver 接口实现的业务逻辑
5. Response Decorators : 结果脱敏或格式转换 (MaskEmail 等)
6. Result Response     : 最终结果渲染响应
*/

func MountFileDemo[T any, C ServerContext[T]](en *Engine[C], biz FileDemoResolver[T]) {
	d, _ := en.Decorator().(Decorator[T])
	v, _ := en.Validator().(Validator[T])
	r, _ := en.Responder().(Responder[T])
	executor := &FileDemoExecutor[T, C]{
		en:  en,
		biz: biz,
		d:   d,
		v:   v,
		r:   r,
	}

	executor.mount()
}

type FileDemoExecutor[T any, C ServerContext[T]] struct {
	en  *Engine[C]
	biz FileDemoResolver[T]
	d   Decorator[T]
	v   Validator[T]
	r   Responder[T]
}

func (e *FileDemoExecutor[T, C]) mount() {

	// --- 注册组: Files ---

	infoUploadAvatar := MethodInfo{
		Module: "FileDemo",
		Group:  "/files",
		Method: "POST",
		Name:   "UploadAvatar",
		Path:   "/files/avatar",
	}
	e.register(infoUploadAvatar, e.handleUploadAvatar)

	infoUploadDocument := MethodInfo{
		Module: "FileDemo",
		Group:  "/files",
		Method: "POST",
		Name:   "UploadDocument",
		Path:   "/files/document",
	}
	e.register(infoUploadDocument, e.handleUploadDocument)

	infoDownloadFile := MethodInfo{
		Module: "FileDemo",
		Group:  "/files",
		Method: "GET",
		Name:   "DownloadFile",
		Path:   "/files/download/:id",
	}
	e.register(infoDownloadFile, e.handleDownloadFile)

	infoExportCsv := MethodInfo{
		Module: "FileDemo",
		Group:  "/files",
		Method: "GET",
		Name:   "ExportCsv",
		Path:   "/files/export/csv",
	}
	e.register(infoExportCsv, e.handleExportCsv)

	infoDownloadDynamic := MethodInfo{
		Module: "FileDemo",
		Group:  "/files",
		Method: "GET",
		Name:   "DownloadDynamic",
		Path:   "/files/dynamic/:id",
	}
	e.register(infoDownloadDynamic, e.handleDownloadDynamic)
}

func (e *FileDemoExecutor[T, C]) register(info MethodInfo, handler HandlerFunc[C]) {
	info.HandlerPos = GetHandlerJumpPath(e.biz, info.Name)
	e.en.Register(info, handler)
}

// handleUploadAvatar 封装了端点的自动化执行流
func (e *FileDemoExecutor[T, C]) handleUploadAvatar(request C, info MethodInfo) {
	native := request.Native()
	var input UploadAvatarInput
	if err := e.bindUploadAvatar(request, &input); err != nil {
		request.RenderJson(e.r.ErrorToStatus(native, err), e.r.BindResData(native, nil, err))
		return
	}
	if err := e.validateUploadAvatar(native, &input); err != nil {
		request.RenderJson(e.r.ErrorToStatus(native, err), e.r.BindResData(native, nil, err))
		return
	}
	result, err := e.biz.UploadAvatar(request.Context(), &input)
	if err != nil {
		request.RenderJson(e.r.ErrorToStatus(native, err), e.r.BindResData(native, nil, err))
		return
	}
	request.RenderJson(201, e.r.BindResData(native, result, nil))
}

// bindUploadAvatar 自动生成的参数提取与转换实现
func (e *FileDemoExecutor[T, C]) bindUploadAvatar(request C, input *UploadAvatarInput) error {
	if err := request.Payload(SourceMultipart, input); err != nil {
		return err
	}
	return nil
}

// validateUploadAvatar 参数验证逻辑
func (e *FileDemoExecutor[T, C]) validateUploadAvatar(ctx T, input *UploadAvatarInput) error {
	if err := e.v.Required(ctx, "userId", input.UserId); err != nil {
		return err
	}
	if input.Avatar != nil {
		if err := e.v.Required(ctx, "avatar", *input.Avatar); err != nil {
			return err
		}
		if err := e.v.FileRule(ctx, "avatar", *input.Avatar, 2097152, []string{"image/jpeg", "image/png"}, "头像仅支持 JPG/PNG 格式，且不超过 2MB"); err != nil {
			return err
		}
	}

	return nil
}

// handleUploadDocument 封装了端点的自动化执行流
func (e *FileDemoExecutor[T, C]) handleUploadDocument(request C, info MethodInfo) {
	native := request.Native()
	var input UploadDocumentInput
	if err := e.bindUploadDocument(request, &input); err != nil {
		request.RenderJson(e.r.ErrorToStatus(native, err), e.r.BindResData(native, nil, err))
		return
	}
	if err := e.validateUploadDocument(native, &input); err != nil {
		request.RenderJson(e.r.ErrorToStatus(native, err), e.r.BindResData(native, nil, err))
		return
	}
	result, err := e.biz.UploadDocument(request.Context(), &input)
	if err != nil {
		request.RenderJson(e.r.ErrorToStatus(native, err), e.r.BindResData(native, nil, err))
		return
	}
	request.RenderJson(201, e.r.BindResData(native, result, nil))
}

// bindUploadDocument 自动生成的参数提取与转换实现
func (e *FileDemoExecutor[T, C]) bindUploadDocument(request C, input *UploadDocumentInput) error {
	if err := request.Payload(SourceMultipart, input); err != nil {
		return err
	}
	return nil
}

// validateUploadDocument 参数验证逻辑
func (e *FileDemoExecutor[T, C]) validateUploadDocument(ctx T, input *UploadDocumentInput) error {
	if err := e.v.Required(ctx, "title", input.Title); err != nil {
		return err
	}
	if input.Description != nil {
	}
	if input.Document != nil {
		if err := e.v.Required(ctx, "document", *input.Document); err != nil {
			return err
		}
		if err := e.v.FileRule(ctx, "document", *input.Document, 10485760, []string{"application/pdf"}, "仅支持 PDF 格式，且不超过 10MB"); err != nil {
			return err
		}
	}
	if input.Cover != nil {
		if err := e.v.FileRule(ctx, "cover", *input.Cover, 1048576, []string{"image/jpeg", "image/png", "image/webp"}, "封面图仅支持 JPG/PNG/WebP 格式，且不超过 1MB"); err != nil {
			return err
		}
	}

	return nil
}

// handleDownloadFile 封装了端点的自动化执行流
func (e *FileDemoExecutor[T, C]) handleDownloadFile(request C, info MethodInfo) {
	native := request.Native()
	var IDVal *int

	if val := request.GetPath("id"); val != "" {
		if v, err := IntFromParam(val); err == nil {
			v2 := v
			IDVal = &v2
		} else {
			request.RenderJson(e.r.ErrorToStatus(native, err), e.r.BindResData(native, nil, err))
			return
		}
	}
	result, err := e.biz.DownloadFile(request.Context(), IDVal)
	if err != nil {
		request.RenderJson(e.r.ErrorToStatus(native, err), e.r.BindResData(native, nil, err))
		return
	}
	if result != nil {
		result.ContentType = "application/pdf"
		request.RenderStream(200, *result)
	}
}

// handleExportCsv 封装了端点的自动化执行流
func (e *FileDemoExecutor[T, C]) handleExportCsv(request C, info MethodInfo) {
	native := request.Native()
	var IdsVal *string

	if val := request.GetQuery("ids"); val != "" {
		IdsVal = &val
	}
	result, err := e.biz.ExportCsv(request.Context(), IdsVal)
	if err != nil {
		request.RenderJson(e.r.ErrorToStatus(native, err), e.r.BindResData(native, nil, err))
		return
	}
	if result != nil {
		result.ContentType = "text/csv"
		request.RenderStream(200, *result)
	}
}

// handleDownloadDynamic 封装了端点的自动化执行流
func (e *FileDemoExecutor[T, C]) handleDownloadDynamic(request C, info MethodInfo) {
	native := request.Native()
	var IDVal *int

	if val := request.GetPath("id"); val != "" {
		if v, err := IntFromParam(val); err == nil {
			v2 := v
			IDVal = &v2
		} else {
			request.RenderJson(e.r.ErrorToStatus(native, err), e.r.BindResData(native, nil, err))
			return
		}
	}
	result, err := e.biz.DownloadDynamic(request.Context(), IDVal)
	if err != nil {
		request.RenderJson(e.r.ErrorToStatus(native, err), e.r.BindResData(native, nil, err))
		return
	}
	if result != nil {
		if result.ContentType == "" {
			result.ContentType = "application/octet-stream"
		}
		request.RenderStream(200, *result)
	}
}
