// Code generated by github.com/xslasd/resgen. DO NOT EDIT.
// This file will be automatically regenerated based on the schema.

package resolver

import (
	"context"
	"time"

	"github.com/xslasd/resgen/examples/scalars"
)

// ==========================================
// 1. Models
// ==========================================

// ScalarInput 输入模型
type ScalarInput struct {
	Time      *time.Time `json:"time"`
	Body_time *time.Time `json:"body_time"`
}

// ScalarInputDTO 数据传输对象
type ScalarInputDTO struct {
	Body_time *int64 `json:"body_time"`
}

func (m *ScalarInput) ToDTO(ctx any) (*ScalarInputDTO, error) {
	if m == nil {
		return nil, nil
	}
	dto := &ScalarInputDTO{}
	if m.Body_time != nil {
		tmpBody_time := scalars.IntTime(*m.Body_time)
		valBody_time, err := tmpBody_time.ToValue(ctx)
		if err != nil {
			return nil, err
		}
		dto.Body_time = &valBody_time
	}
	return dto, nil
}

func (m *ScalarInput) FromDTO(ctx any, dto *ScalarInputDTO) error {
	if m == nil || dto == nil {
		return nil
	}
	if dto.Body_time != nil {
		var tmp scalars.IntTime
		if err := tmp.FromValue(ctx, *dto.Body_time); err != nil {
			return err
		}
		targetVal := time.Time(tmp)
		m.Body_time = &targetVal
	}
	return nil
}

// ComplexA 输出模型
type ComplexA struct {
	Name      string    `json:"name"`
	ScalarVal time.Time `json:"scalar_val"`
}

// ComplexADTO 数据传输对象
type ComplexADTO struct {
	Name      string `json:"name"`
	ScalarVal int64  `json:"scalar_val"`
}

func (m *ComplexA) ToDTO(ctx any) (*ComplexADTO, error) {
	if m == nil {
		return nil, nil
	}
	dto := &ComplexADTO{}
	dto.Name = m.Name
	tmpScalarVal := scalars.IntTime(m.ScalarVal)
	valScalarVal, err := tmpScalarVal.ToValue(ctx)
	if err != nil {
		return nil, err
	}
	dto.ScalarVal = valScalarVal
	return dto, nil
}

func (m *ComplexA) FromDTO(ctx any, dto *ComplexADTO) error {
	if m == nil || dto == nil {
		return nil
	}
	m.Name = dto.Name
	var tmpScalarVal scalars.IntTime
	if err := tmpScalarVal.FromValue(ctx, dto.ScalarVal); err != nil {
		return err
	}
	m.ScalarVal = time.Time(tmpScalarVal)
	return nil
}

// ComplexB 输出模型
type ComplexB struct {
	Title     string       `json:"title"`
	ASingle   ComplexA     `json:"a_single"`
	APointer  *ComplexA    `json:"a_pointer"`
	AArrayVal []ComplexA   `json:"a_array_val"`
	AArrayPtr *[]*ComplexA `json:"a_array_ptr"`
}

// ComplexBDTO 数据传输对象
type ComplexBDTO struct {
	Title     string          `json:"title"`
	ASingle   ComplexADTO     `json:"a_single"`
	APointer  *ComplexADTO    `json:"a_pointer"`
	AArrayVal []ComplexADTO   `json:"a_array_val"`
	AArrayPtr *[]*ComplexADTO `json:"a_array_ptr"`
}

func (m *ComplexB) ToDTO(ctx any) (*ComplexBDTO, error) {
	if m == nil {
		return nil, nil
	}
	dto := &ComplexBDTO{}
	dto.Title = m.Title
	val, err := (&m.ASingle).ToDTO(ctx)
	if err != nil {
		return nil, err
	}
	if val != nil {
		dto.ASingle = *val
	}
	if m.APointer != nil {
		val, err := m.APointer.ToDTO(ctx)
		if err != nil {
			return nil, err
		}
		dto.APointer = val
	}
	if m.AArrayVal != nil {
		list := make([]ComplexADTO, len(m.AArrayVal))
		for i, item := range m.AArrayVal {
			dtoItem, err := (&item).ToDTO(ctx)
			if err != nil {
				return nil, err
			}
			if dtoItem != nil {
				list[i] = *dtoItem
			}
		}
		dto.AArrayVal = list
	}
	if m.AArrayPtr != nil {
		list := make([]*ComplexADTO, len(*m.AArrayPtr))
		for i, item := range *m.AArrayPtr {
			dtoItem, err := item.ToDTO(ctx)
			if err != nil {
				return nil, err
			}
			list[i] = dtoItem
		}
		dto.AArrayPtr = &list
	}
	return dto, nil
}

func (m *ComplexB) FromDTO(ctx any, dto *ComplexBDTO) error {
	if m == nil || dto == nil {
		return nil
	}
	m.Title = dto.Title
	if err := (&m.ASingle).FromDTO(ctx, &dto.ASingle); err != nil {
		return err
	}
	if dto.APointer != nil {
		if m.APointer == nil {
			m.APointer = &ComplexA{}
		}
		if err := m.APointer.FromDTO(ctx, dto.APointer); err != nil {
			return err
		}
	}
	if dto.AArrayVal != nil {
		list := make([]ComplexA, len(dto.AArrayVal))
		for i, item := range dto.AArrayVal {
			if err := list[i].FromDTO(ctx, &item); err != nil {
				return err
			}
		}
		m.AArrayVal = list
	}
	if dto.AArrayPtr != nil {
		list := make([]*ComplexA, len(*dto.AArrayPtr))
		for i, item := range *dto.AArrayPtr {
			var modelItem ComplexA
			if err := modelItem.FromDTO(ctx, item); err != nil {
				return err
			}
			list[i] = &modelItem
		}
		m.AArrayPtr = &list
	}
	return nil
}

// ScalarOutput 输出模型
type ScalarOutput struct {
	Time          *time.Time `json:"time"`
	NestedComplex *ComplexB  `json:"nested_complex"`
}

// ScalarOutputDTO 数据传输对象
type ScalarOutputDTO struct {
	Time          *int64       `json:"time"`
	NestedComplex *ComplexBDTO `json:"nested_complex"`
}

func (m *ScalarOutput) ToDTO(ctx any) (*ScalarOutputDTO, error) {
	if m == nil {
		return nil, nil
	}
	dto := &ScalarOutputDTO{}
	if m.Time != nil {
		tmpTime := scalars.IntTime(*m.Time)
		valTime, err := tmpTime.ToValue(ctx)
		if err != nil {
			return nil, err
		}
		dto.Time = &valTime
	}
	if m.NestedComplex != nil {
		val, err := m.NestedComplex.ToDTO(ctx)
		if err != nil {
			return nil, err
		}
		dto.NestedComplex = val
	}
	return dto, nil
}

func (m *ScalarOutput) FromDTO(ctx any, dto *ScalarOutputDTO) error {
	if m == nil || dto == nil {
		return nil
	}
	if dto.Time != nil {
		var tmp scalars.IntTime
		if err := tmp.FromValue(ctx, *dto.Time); err != nil {
			return err
		}
		targetVal := time.Time(tmp)
		m.Time = &targetVal
	}
	if dto.NestedComplex != nil {
		if m.NestedComplex == nil {
			m.NestedComplex = &ComplexB{}
		}
		if err := m.NestedComplex.FromDTO(ctx, dto.NestedComplex); err != nil {
			return err
		}
	}
	return nil
}

// ==========================================
// 2. Resolver Interface
// ==========================================

// ScalarCenterResolver 定义模块业务逻辑接口
type ScalarCenterResolver[T any] interface {

	// TestScalar GET /scalar/test/:time
	TestScalar(ctx context.Context, time *time.Time) (*ScalarOutput, error)

	// TestScalarBody POST /scalar/test
	TestScalarBody(ctx context.Context, input *ScalarInput) (*ScalarOutput, error)
}

// ==========================================
// 3. Executor / Binders
// ==========================================

/*
Resgen 自动化执行流说明:
1. Request Decorators  : 全局与特化请求拦截 (Auth, RateLimit 等)
2. Binding & Validation: 自动参数绑定与核心规则校验
3. Invoke Decorators   : 业务调用前的特化处理 (OwnerCheck 等)
4. Business Logic      : 调用 Resolver 接口实现的业务逻辑
5. Response Decorators : 结果脱敏或格式转换 (MaskEmail 等)
6. Result Response     : 最终结果渲染响应
*/

func MountScalarCenter[T any, C ServerContext[T]](en *Engine[C], biz ScalarCenterResolver[T]) {
	d, _ := en.Decorator().(Decorator[T])
	v, _ := en.Validator().(Validator[T])
	r, _ := en.Responder().(Responder[T])
	executor := &ScalarCenterExecutor[T, C]{
		en:  en,
		biz: biz,
		d:   d,
		v:   v,
		r:   r,
	}

	executor.mount()
}

type ScalarCenterExecutor[T any, C ServerContext[T]] struct {
	en  *Engine[C]
	biz ScalarCenterResolver[T]
	d   Decorator[T]
	v   Validator[T]
	r   Responder[T]
}

func (e *ScalarCenterExecutor[T, C]) mount() {

	// --- 注册组: ScalarGroup ---

	infoTestScalar := MethodInfo{
		Module: "ScalarCenter",
		Group:  "/scalar",
		Method: "GET",
		Name:   "TestScalar",
		Path:   "/scalar/test/:time",
	}
	e.en.Register(infoTestScalar, e.handleTestScalar)

	infoTestScalarBody := MethodInfo{
		Module: "ScalarCenter",
		Group:  "/scalar",
		Method: "POST",
		Name:   "TestScalarBody",
		Path:   "/scalar/test",
	}
	e.en.Register(infoTestScalarBody, e.handleTestScalarBody)
}

// handleTestScalar 封装了端点的自动化执行流
func (e *ScalarCenterExecutor[T, C]) handleTestScalar(request C, info MethodInfo) {
	var timeVal *time.Time
	if val := request.GetPath("time"); val != "" {
		var tmp scalars.IntTime
		if err := tmp.FromParam(request.Native(), val); err != nil {
			request.RenderJson(e.r.ErrorToStatus(request.Native(), err), e.r.BindResData(request.Native(), nil, err))
			return
		}
		targetVal := time.Time(tmp)
		timeVal = &targetVal
	}
	result, err := e.biz.TestScalar(request.Context(), timeVal)
	if err != nil {
		request.RenderJson(e.r.ErrorToStatus(request.Native(), err), e.r.BindResData(request.Native(), nil, err))
		return
	}
	dtoResult, dErr := result.ToDTO(request.Native())
	if dErr != nil {
		request.RenderJson(e.r.ErrorToStatus(request.Native(), dErr), e.r.BindResData(request.Native(), nil, dErr))
		return
	}
	request.RenderJson(200, e.r.BindResData(request.Native(), dtoResult, nil))
}

// handleTestScalarBody 封装了端点的自动化执行流
func (e *ScalarCenterExecutor[T, C]) handleTestScalarBody(request C, info MethodInfo) {
	var input ScalarInput
	if err := e.bindTestScalarBody(request, &input); err != nil {
		request.RenderJson(e.r.ErrorToStatus(request.Native(), err), e.r.BindResData(request.Native(), nil, err))
		return
	}
	result, err := e.biz.TestScalarBody(request.Context(), &input)
	if err != nil {
		request.RenderJson(e.r.ErrorToStatus(request.Native(), err), e.r.BindResData(request.Native(), nil, err))
		return
	}
	dtoResult, dErr := result.ToDTO(request.Native())
	if dErr != nil {
		request.RenderJson(e.r.ErrorToStatus(request.Native(), dErr), e.r.BindResData(request.Native(), nil, dErr))
		return
	}
	request.RenderJson(200, e.r.BindResData(request.Native(), dtoResult, nil))
}

// bindTestScalarBody 自动生成的参数提取与转换实现
func (e *ScalarCenterExecutor[T, C]) bindTestScalarBody(request C, input *ScalarInput) error {
	var dto ScalarInputDTO
	if err := request.Payload(SourceJson, &dto); err != nil {
		return err
	}
	if err := input.FromDTO(request.Native(), &dto); err != nil {
		return err
	}
	return nil
}
