// Code generated by github.com/xslasd/resgen v0.7.2. DO NOT EDIT.
// This file will be automatically regenerated based on the schema.

package resolver

import (
	"context"

	"github.com/xslasd/resgen/examples/scalars"
)

// ==========================================
// 1. Enums
// ==========================================

// ==========================================
// 2. Models
// ==========================================

// 使用标量作为模型字段
type Event struct {
	ID        int              `json:"id"`
	Name      string           `json:"name"`
	StartTime scalars.IntTime  `json:"start_time"`
	EndTime   *scalars.IntTime `json:"end_time"`
	CreatedAt *scalars.IntTime `json:"created_at"`
}

// CreateEventInput 输入模型
type CreateEventInput struct {
	Name string `json:"name"`
	// 使用 @alias 自定义传输别名，兼容老前端/老系统不规范命名
	StartTime scalars.IntTime `json:"st_time"`
	EndTime   scalars.IntTime `json:"end_time"`
}

// QueryEventsInput 输入模型
type QueryEventsInput struct {
	After  *scalars.IntTime `json:"from_tm"`
	Before *scalars.IntTime `json:"to_tm"`
	Page   *int             `json:"page"`
	Size   *int             `json:"size"`
}

// ==========================================
// 2. Resolver Interface
// ==========================================

// ScalarDemoResolver 定义模块业务逻辑接口
type ScalarDemoResolver[T any] interface {

	// 标量作为路径参数（@path），由 FromParam 处理字符串解析
	//
	// GET /events/:startTime
	GetEventByTime(ctx context.Context, startTime *scalars.IntTime) (*Event, error)

	// 标量作为 Query 参数，GET 请求自动展开
	//
	// GET /events/list
	ListEvents(ctx context.Context, input *QueryEventsInput) (*[]*Event, error)

	// 标量在请求 Body 中，由序列化层处理
	//
	// POST /events/create
	CreateEvent(ctx context.Context, input *CreateEventInput) (*Event, error)
}

// ==========================================
// 3. Executor / Binders
// ==========================================

/*
Resgen 自动化执行流说明:
1. Request Decorators  : 全局与特化请求拦截 (Auth, RateLimit 等)
2. Binding & Validation: 自动参数绑定与核心规则校验
3. Invoke Decorators   : 业务调用前的特化处理 (OwnerCheck 等)
4. Business Logic      : 调用 Resolver 接口实现的业务逻辑
5. Response Decorators : 结果脱敏或格式转换 (MaskEmail 等)
6. Result Response     : 最终结果渲染响应
*/

func MountScalarDemo[T any, C ServerContext[T]](en *Engine[C], biz ScalarDemoResolver[T]) {
	d, _ := en.Decorator().(Decorator[T])
	v, _ := en.Validator().(Validator[T])
	r, _ := en.Responder().(Responder[T])
	executor := &ScalarDemoExecutor[T, C]{
		en:  en,
		biz: biz,
		d:   d,
		v:   v,
		r:   r,
	}

	executor.mount()
}

type ScalarDemoExecutor[T any, C ServerContext[T]] struct {
	en  *Engine[C]
	biz ScalarDemoResolver[T]
	d   Decorator[T]
	v   Validator[T]
	r   Responder[T]
}

func (e *ScalarDemoExecutor[T, C]) mount() {

	// --- 注册组: Events ---

	infoGetEventByTime := MethodInfo{
		Module: "ScalarDemo",
		Group:  "/events",
		Method: "GET",
		Name:   "GetEventByTime",
		Path:   "/events/:startTime",
	}
	e.register(infoGetEventByTime, e.handleGetEventByTime)

	infoListEvents := MethodInfo{
		Module: "ScalarDemo",
		Group:  "/events",
		Method: "GET",
		Name:   "ListEvents",
		Path:   "/events/list",
	}
	e.register(infoListEvents, e.handleListEvents)

	infoCreateEvent := MethodInfo{
		Module: "ScalarDemo",
		Group:  "/events",
		Method: "POST",
		Name:   "CreateEvent",
		Path:   "/events/create",
	}
	e.register(infoCreateEvent, e.handleCreateEvent)
}

func (e *ScalarDemoExecutor[T, C]) register(info MethodInfo, handler HandlerFunc[C]) {
	info.HandlerPos = GetHandlerJumpPath(e.biz, info.Name)
	e.en.Register(info, handler)
}

// handleGetEventByTime 封装了端点的自动化执行流
func (e *ScalarDemoExecutor[T, C]) handleGetEventByTime(request C, info MethodInfo) {
	native := request.Native()
	if err := e.d.Auth(native, info, "events:get"); err != nil {
		request.RenderJson(e.r.ErrorToStatus(native, err), e.r.BindResData(native, nil, err))
		return
	}
	var StartTimeVal *scalars.IntTime

	if val := request.GetPath("startTime"); val != "" {
		var tmp scalars.IntTime
		if err := tmp.FromParam(native, val); err != nil {
			request.RenderJson(e.r.ErrorToStatus(native, err), e.r.BindResData(native, nil, err))
			return
		}
		targetVal := scalars.IntTime(tmp)
		StartTimeVal = &targetVal
	}
	result, err := e.biz.GetEventByTime(request.Context(), StartTimeVal)
	if err != nil {
		request.RenderJson(e.r.ErrorToStatus(native, err), e.r.BindResData(native, nil, err))
		return
	}
	request.RenderJson(200, e.r.BindResData(native, result, nil))
}

// handleListEvents 封装了端点的自动化执行流
func (e *ScalarDemoExecutor[T, C]) handleListEvents(request C, info MethodInfo) {
	native := request.Native()
	if err := e.d.Auth(native, info, "events:list"); err != nil {
		request.RenderJson(e.r.ErrorToStatus(native, err), e.r.BindResData(native, nil, err))
		return
	}
	var input QueryEventsInput
	if err := e.bindListEvents(request, &input); err != nil {
		request.RenderJson(e.r.ErrorToStatus(native, err), e.r.BindResData(native, nil, err))
		return
	}
	result, err := e.biz.ListEvents(request.Context(), &input)
	if err != nil {
		request.RenderJson(e.r.ErrorToStatus(native, err), e.r.BindResData(native, nil, err))
		return
	}
	request.RenderJson(200, e.r.BindResData(native, result, nil))
}

// bindListEvents 自动生成的参数提取与转换实现
func (e *ScalarDemoExecutor[T, C]) bindListEvents(request C, input *QueryEventsInput) error {
	if val := request.GetQuery("from_tm"); val != "" {
		var tmp scalars.IntTime
		if err := tmp.FromParam(request.Native(), val); err != nil {
			return err
		}
		targetVal := scalars.IntTime(tmp)
		input.After = &targetVal
	}
	if val := request.GetQuery("to_tm"); val != "" {
		var tmp scalars.IntTime
		if err := tmp.FromParam(request.Native(), val); err != nil {
			return err
		}
		targetVal := scalars.IntTime(tmp)
		input.Before = &targetVal
	}
	if val := request.GetQuery("page"); val != "" {
		if v, err := IntFromParam(val); err == nil {
			v2 := v
			input.Page = &v2
		} else {
			return err
		}
	}
	if val := request.GetQuery("size"); val != "" {
		if v, err := IntFromParam(val); err == nil {
			v2 := v
			input.Size = &v2
		} else {
			return err
		}
	}
	return nil
}

// handleCreateEvent 封装了端点的自动化执行流
func (e *ScalarDemoExecutor[T, C]) handleCreateEvent(request C, info MethodInfo) {
	native := request.Native()
	var input CreateEventInput
	if err := e.bindCreateEvent(request, &input); err != nil {
		request.RenderJson(e.r.ErrorToStatus(native, err), e.r.BindResData(native, nil, err))
		return
	}
	if err := e.validateCreateEvent(native, &input); err != nil {
		request.RenderJson(e.r.ErrorToStatus(native, err), e.r.BindResData(native, nil, err))
		return
	}
	result, err := e.biz.CreateEvent(request.Context(), &input)
	if err != nil {
		request.RenderJson(e.r.ErrorToStatus(native, err), e.r.BindResData(native, nil, err))
		return
	}
	request.RenderJson(201, e.r.BindResData(native, result, nil))
}

// bindCreateEvent 自动生成的参数提取与转换实现
func (e *ScalarDemoExecutor[T, C]) bindCreateEvent(request C, input *CreateEventInput) error {
	if err := request.Payload(SourceJSON, input); err != nil {
		return err
	}
	return nil
}

// validateCreateEvent 参数验证逻辑
func (e *ScalarDemoExecutor[T, C]) validateCreateEvent(ctx T, input *CreateEventInput) error {
	if err := e.v.Required(ctx, "name", input.Name); err != nil {
		return err
	}
	if err := e.v.Required(ctx, "st_time", input.StartTime); err != nil {
		return err
	}
	if err := e.v.Required(ctx, "end_time", input.EndTime); err != nil {
		return err
	}

	return nil
}
