// Code generated by github.com/xslasd/resgen v0.3.3. DO NOT EDIT.
// This file will be automatically regenerated based on the schema.

package resolver

import (
	"context"
	"fmt"
)

// ==========================================
// 1. Models
// ==========================================

// Product 输出模型
type Product struct {
	Id    int     `json:"id"`
	Name  string  `json:"name"`
	Price float64 `json:"price"`
}

// CreateProductInput 输入模型
type CreateProductInput struct {
	Name  string  `json:"name"`
	Price float64 `json:"price"`
}

// ListProductsArgs 输入模型
type ListProductsArgs struct {
	Page *int `json:"page"`
	Size *int `json:"size"`
}

// ==========================================
// 2. Resolver Interface
// ==========================================

// StatusDemoResolver 定义模块业务逻辑接口
type StatusDemoResolver[T any] interface {

	// GetProduct GET /products/:id
	GetProduct(ctx context.Context, id *int) (*Product, error)

	// CreateProduct POST /products/create
	CreateProduct(ctx context.Context, input *CreateProductInput) (*Product, error)

	// BatchUpdate POST /products/batch-update
	BatchUpdate(ctx context.Context, ids []int) (*string, error)

	// DeleteProduct DELETE /products/:id
	DeleteProduct(ctx context.Context, id *int) (*string, error)

	// ListProducts GET /products/list
	ListProducts(ctx context.Context, input *ListProductsArgs) ([]Product, error)

	// GetRawProduct GET /raw/product/:id
	GetRawProduct(ctx context.Context, id *int) (*Product, error)

	// GetRawProducts GET /raw/products
	GetRawProducts(ctx context.Context, page *int) (*[]*Product, error)
}

// ==========================================
// 3. Executor / Binders
// ==========================================

/*
Resgen 自动化执行流说明:
1. Request Decorators  : 全局与特化请求拦截 (Auth, RateLimit 等)
2. Binding & Validation: 自动参数绑定与核心规则校验
3. Invoke Decorators   : 业务调用前的特化处理 (OwnerCheck 等)
4. Business Logic      : 调用 Resolver 接口实现的业务逻辑
5. Response Decorators : 结果脱敏或格式转换 (MaskEmail 等)
6. Result Response     : 最终结果渲染响应
*/

func MountStatusDemo[T any, C ServerContext[T]](en *Engine[C], biz StatusDemoResolver[T]) {
	d, _ := en.Decorator().(Decorator[T])
	v, _ := en.Validator().(Validator[T])
	r, _ := en.Responder().(Responder[T])
	executor := &StatusDemoExecutor[T, C]{
		en:  en,
		biz: biz,
		d:   d,
		v:   v,
		r:   r,
	}

	executor.mount()
}

type StatusDemoExecutor[T any, C ServerContext[T]] struct {
	en  *Engine[C]
	biz StatusDemoResolver[T]
	d   Decorator[T]
	v   Validator[T]
	r   Responder[T]
}

func (e *StatusDemoExecutor[T, C]) mount() {

	// --- 注册组: Products ---

	infoGetProduct := MethodInfo{
		Module: "StatusDemo",
		Group:  "/products",
		Method: "GET",
		Name:   "GetProduct",
		Path:   "/products/:id",
	}
	e.register(infoGetProduct, e.handleGetProduct)

	infoCreateProduct := MethodInfo{
		Module: "StatusDemo",
		Group:  "/products",
		Method: "POST",
		Name:   "CreateProduct",
		Path:   "/products/create",
	}
	e.register(infoCreateProduct, e.handleCreateProduct)

	infoBatchUpdate := MethodInfo{
		Module: "StatusDemo",
		Group:  "/products",
		Method: "POST",
		Name:   "BatchUpdate",
		Path:   "/products/batch-update",
	}
	e.register(infoBatchUpdate, e.handleBatchUpdate)

	infoDeleteProduct := MethodInfo{
		Module: "StatusDemo",
		Group:  "/products",
		Method: "DELETE",
		Name:   "DeleteProduct",
		Path:   "/products/:id",
	}
	e.register(infoDeleteProduct, e.handleDeleteProduct)

	infoListProducts := MethodInfo{
		Module: "StatusDemo",
		Group:  "/products",
		Method: "GET",
		Name:   "ListProducts",
		Path:   "/products/list",
	}
	e.register(infoListProducts, e.handleListProducts)

	// --- 注册组: Raw ---

	infoGetRawProduct := MethodInfo{
		Module: "StatusDemo",
		Group:  "/raw",
		Method: "GET",
		Name:   "GetRawProduct",
		Path:   "/raw/product/:id",
	}
	e.register(infoGetRawProduct, e.handleGetRawProduct)

	infoGetRawProducts := MethodInfo{
		Module: "StatusDemo",
		Group:  "/raw",
		Method: "GET",
		Name:   "GetRawProducts",
		Path:   "/raw/products",
	}
	e.register(infoGetRawProducts, e.handleGetRawProducts)
}

func (e *StatusDemoExecutor[T, C]) register(info MethodInfo, handler HandlerFunc[C]) {
	info.HandlerPos = GetHandlerJumpPath(e.biz, info.Name)
	e.en.Register(info, handler)
}

// handleGetProduct 封装了端点的自动化执行流
func (e *StatusDemoExecutor[T, C]) handleGetProduct(request C, info MethodInfo) {
	native := request.Native()
	var idVal *int

	if val := request.GetPath("id"); val != "" {
		if v, err := IntFromParam(val); err == nil {
			v2 := v
			idVal = &v2
		} else {
			request.RenderJson(e.r.ErrorToStatus(native, err), e.r.BindResData(native, nil, err))
			return
		}
	}
	result, err := e.biz.GetProduct(request.Context(), idVal)
	if err != nil {
		request.RenderJson(e.r.ErrorToStatus(native, err), e.r.BindResData(native, nil, err))
		return
	}
	request.RenderJson(200, e.r.BindResData(native, result, nil))
}

// handleCreateProduct 封装了端点的自动化执行流
func (e *StatusDemoExecutor[T, C]) handleCreateProduct(request C, info MethodInfo) {
	native := request.Native()
	var input CreateProductInput
	if err := e.bindCreateProduct(request, &input); err != nil {
		request.RenderJson(e.r.ErrorToStatus(native, err), e.r.BindResData(native, nil, err))
		return
	}
	if err := e.validateCreateProduct(native, &input); err != nil {
		request.RenderJson(e.r.ErrorToStatus(native, err), e.r.BindResData(native, nil, err))
		return
	}
	result, err := e.biz.CreateProduct(request.Context(), &input)
	if err != nil {
		request.RenderJson(e.r.ErrorToStatus(native, err), e.r.BindResData(native, nil, err))
		return
	}
	request.RenderJson(201, e.r.BindResData(native, result, nil))
}

// bindCreateProduct 自动生成的参数提取与转换实现
func (e *StatusDemoExecutor[T, C]) bindCreateProduct(request C, input *CreateProductInput) error {
	if err := request.Payload(SourceJson, input); err != nil {
		return err
	}
	return nil
}

// validateCreateProduct 参数验证逻辑
func (e *StatusDemoExecutor[T, C]) validateCreateProduct(ctx T, input *CreateProductInput) error {
	// Pass 1: Required validations
	if err := e.v.Required(ctx, "name", input.Name); err != nil {
		return err
	}
	if err := e.v.Required(ctx, "price", input.Price); err != nil {
		return err
	}

	// Pass 2: Other validations
	return nil
}

// handleBatchUpdate 封装了端点的自动化执行流
func (e *StatusDemoExecutor[T, C]) handleBatchUpdate(request C, info MethodInfo) {
	native := request.Native()
	var idsVal []int

	if val := request.GetQuery("ids"); val != "" {
		// 不支持的基础数据类型: []int
		request.RenderJson(e.r.ErrorToStatus(native, fmt.Errorf("未支持的参数物理类型: %s", "[]int")), e.r.BindResData(native, nil, fmt.Errorf("未支持的参数物理类型: %s", "[]int")))
		return
	}
	result, err := e.biz.BatchUpdate(request.Context(), idsVal)
	if err != nil {
		request.RenderJson(e.r.ErrorToStatus(native, err), e.r.BindResData(native, nil, err))
		return
	}
	request.RenderJson(202, e.r.BindResData(native, result, nil))
}

// handleDeleteProduct 封装了端点的自动化执行流
func (e *StatusDemoExecutor[T, C]) handleDeleteProduct(request C, info MethodInfo) {
	native := request.Native()
	var idVal *int

	if val := request.GetPath("id"); val != "" {
		if v, err := IntFromParam(val); err == nil {
			v2 := v
			idVal = &v2
		} else {
			request.RenderJson(e.r.ErrorToStatus(native, err), err.Error())
			return
		}
	}
	result, err := e.biz.DeleteProduct(request.Context(), idVal)
	if err != nil {
		request.RenderJson(e.r.ErrorToStatus(native, err), err.Error())
		return
	}
	request.RenderJson(204, result)
}

// handleListProducts 封装了端点的自动化执行流
func (e *StatusDemoExecutor[T, C]) handleListProducts(request C, info MethodInfo) {
	native := request.Native()
	var input ListProductsArgs
	if err := e.bindListProducts(request, &input); err != nil {
		request.RenderJson(e.r.ErrorToStatus(native, err), e.r.BindPageData(native, nil, err))
		return
	}
	result, err := e.biz.ListProducts(request.Context(), &input)
	if err != nil {
		request.RenderJson(e.r.ErrorToStatus(native, err), e.r.BindPageData(native, nil, err))
		return
	}
	request.RenderJson(200, e.r.BindPageData(native, result, nil))
}

// bindListProducts 自动生成的参数提取与转换实现
func (e *StatusDemoExecutor[T, C]) bindListProducts(request C, input *ListProductsArgs) error {
	if val := request.GetQuery("page"); val != "" {
		if v, err := IntFromParam(val); err == nil {
			v2 := v
			input.Page = &v2
		} else {
			return err
		}
	}
	if val := request.GetQuery("size"); val != "" {
		if v, err := IntFromParam(val); err == nil {
			v2 := v
			input.Size = &v2
		} else {
			return err
		}
	}
	return nil
}

// handleGetRawProduct 封装了端点的自动化执行流
func (e *StatusDemoExecutor[T, C]) handleGetRawProduct(request C, info MethodInfo) {
	native := request.Native()
	var idVal *int

	if val := request.GetPath("id"); val != "" {
		if v, err := IntFromParam(val); err == nil {
			v2 := v
			idVal = &v2
		} else {
			request.RenderJson(e.r.ErrorToStatus(native, err), e.r.BindResData(native, nil, err))
			return
		}
	}
	result, err := e.biz.GetRawProduct(request.Context(), idVal)
	if err != nil {
		request.RenderJson(e.r.ErrorToStatus(native, err), e.r.BindResData(native, nil, err))
		return
	}
	request.RenderJson(200, result)
}

// handleGetRawProducts 封装了端点的自动化执行流
func (e *StatusDemoExecutor[T, C]) handleGetRawProducts(request C, info MethodInfo) {
	native := request.Native()
	var pageVal *int

	if val := request.GetQuery("page"); val != "" {
		if v, err := IntFromParam(val); err == nil {
			v2 := v
			pageVal = &v2
		} else {
			request.RenderJson(e.r.ErrorToStatus(native, err), e.r.BindResData(native, nil, err))
			return
		}
	}
	result, err := e.biz.GetRawProducts(request.Context(), pageVal)
	if err != nil {
		request.RenderJson(e.r.ErrorToStatus(native, err), e.r.BindResData(native, nil, err))
		return
	}
	request.RenderJson(200, e.r.BindResData(native, result, nil))
}
