// Code generated by github.com/xslasd/resgen. DO NOT EDIT.
// This file will be automatically regenerated based on the schema.

package resolver

import (
	"context"
	"time"

	"github.com/xslasd/resgen/examples/scalars"
)

// ==========================================
// 1. Models
// ==========================================

// CreateTaskInput 输入模型
type CreateTaskInput struct {
	Title  string     `json:"title"`
	Period TaskPeriod `json:"period"`
}

// CreateTaskInputDTO 数据传输对象
type CreateTaskInputDTO struct {
	Title  string        `json:"title"`
	Period TaskPeriodDTO `json:"period"`
}

func (m *CreateTaskInput) ToDTO(ctx any) (*CreateTaskInputDTO, error) {
	if m == nil {
		return nil, nil
	}
	dto := &CreateTaskInputDTO{}
	dto.Title = m.Title
	val, err := (&m.Period).ToDTO(ctx)
	if err != nil {
		return nil, err
	}
	if val != nil {
		dto.Period = *val
	}
	return dto, nil
}

func (m *CreateTaskInput) FromDTO(ctx any, dto *CreateTaskInputDTO) error {
	if m == nil || dto == nil {
		return nil
	}
	m.Title = dto.Title
	if err := (&m.Period).FromDTO(ctx, &dto.Period); err != nil {
		return err
	}
	return nil
}

// TaskPeriod 输入模型
type TaskPeriod struct {
	StartTime time.Time `json:"start_time"`
	EndTime   time.Time `json:"end_time"`
}

// TaskPeriodDTO 数据传输对象
type TaskPeriodDTO struct {
	StartTime int64 `json:"start_time"`
	EndTime   int64 `json:"end_time"`
}

func (m *TaskPeriod) ToDTO(ctx any) (*TaskPeriodDTO, error) {
	if m == nil {
		return nil, nil
	}
	dto := &TaskPeriodDTO{}
	tmpStartTime := scalars.IntTime(m.StartTime)
	valStartTime, err := tmpStartTime.ToValue(ctx)
	if err != nil {
		return nil, err
	}
	dto.StartTime = valStartTime
	tmpEndTime := scalars.IntTime(m.EndTime)
	valEndTime, err := tmpEndTime.ToValue(ctx)
	if err != nil {
		return nil, err
	}
	dto.EndTime = valEndTime
	return dto, nil
}

func (m *TaskPeriod) FromDTO(ctx any, dto *TaskPeriodDTO) error {
	if m == nil || dto == nil {
		return nil
	}
	var tmpStartTime scalars.IntTime
	if err := tmpStartTime.FromValue(ctx, dto.StartTime); err != nil {
		return err
	}
	m.StartTime = time.Time(tmpStartTime)
	var tmpEndTime scalars.IntTime
	if err := tmpEndTime.FromValue(ctx, dto.EndTime); err != nil {
		return err
	}
	m.EndTime = time.Time(tmpEndTime)
	return nil
}

// GetTasksInput 输入模型
type GetTasksInput struct {
	Page *int `json:"page"`
	Size *int `json:"size"`
}

// ==========================================
// 2. Resolver Interface
// ==========================================

// TaskCenterResolver 定义模块业务逻辑接口
type TaskCenterResolver[T any] interface {

	// CreateTask POST /tasks/create
	CreateTask(ctx context.Context, input *CreateTaskInput) (*string, error)

	// GetTasks GET /tasks/list
	GetTasks(ctx context.Context, input *GetTasksInput) (*string, error)
}

// ==========================================
// 3. Executor / Binders
// ==========================================

/*
Resgen 自动化执行流说明:
1. Request Decorators  : 全局与特化请求拦截 (Auth, RateLimit 等)
2. Binding & Validation: 自动参数绑定与核心规则校验
3. Invoke Decorators   : 业务调用前的特化处理 (OwnerCheck 等)
4. Business Logic      : 调用 Resolver 接口实现的业务逻辑
5. Response Decorators : 结果脱敏或格式转换 (MaskEmail 等)
6. Result Response     : 最终结果渲染响应
*/

func MountTaskCenter[T any, C ServerContext[T]](en *Engine[C], biz TaskCenterResolver[T]) {
	d, _ := en.Decorator().(Decorator[T])
	v, _ := en.Validator().(Validator[T])
	r, _ := en.Responder().(Responder[T])
	executor := &TaskCenterExecutor[T, C]{
		en:  en,
		biz: biz,
		d:   d,
		v:   v,
		r:   r,
	}

	executor.mount()
}

type TaskCenterExecutor[T any, C ServerContext[T]] struct {
	en  *Engine[C]
	biz TaskCenterResolver[T]
	d   Decorator[T]
	v   Validator[T]
	r   Responder[T]
}

func (e *TaskCenterExecutor[T, C]) mount() {

	// --- 注册组: Tasks ---

	infoCreateTask := MethodInfo{
		Module: "TaskCenter",
		Group:  "/tasks",
		Method: "POST",
		Name:   "CreateTask",
		Path:   "/tasks/create",
	}
	e.en.Register(infoCreateTask, e.handleCreateTask)

	infoGetTasks := MethodInfo{
		Module: "TaskCenter",
		Group:  "/tasks",
		Method: "GET",
		Name:   "GetTasks",
		Path:   "/tasks/list",
	}
	e.en.Register(infoGetTasks, e.handleGetTasks)
}

// handleCreateTask 封装了端点的自动化执行流
func (e *TaskCenterExecutor[T, C]) handleCreateTask(request C, info MethodInfo) {
	var input CreateTaskInput
	if err := e.bindCreateTask(request, &input); err != nil {
		request.RenderJson(e.r.ErrorToStatus(request.Native(), err), e.r.BindResData(request.Native(), nil, err))
		return
	}
	if err := e.validateCreateTask(request.Native(), &input); err != nil {
		request.RenderJson(e.r.ErrorToStatus(request.Native(), err), e.r.BindResData(request.Native(), nil, err))
		return
	}
	result, err := e.biz.CreateTask(request.Context(), &input)
	if err != nil {
		request.RenderJson(e.r.ErrorToStatus(request.Native(), err), e.r.BindResData(request.Native(), nil, err))
		return
	}
	request.RenderJson(200, e.r.BindResData(request.Native(), result, nil))
}

// bindCreateTask 自动生成的参数提取与转换实现
func (e *TaskCenterExecutor[T, C]) bindCreateTask(request C, input *CreateTaskInput) error {
	var dto CreateTaskInputDTO
	if err := request.Payload(SourceJson, &dto); err != nil {
		return err
	}
	if err := input.FromDTO(request.Native(), &dto); err != nil {
		return err
	}
	return nil
}

// validateCreateTask 参数验证逻辑
func (e *TaskCenterExecutor[T, C]) validateCreateTask(ctx T, input *CreateTaskInput) error {
	// Pass 1: Required validations
	if err := e.v.Required(ctx, "title", input.Title); err != nil {
		return err
	}
	if err := e.v.Required(ctx, "period", input.Period); err != nil {
		return err
	}
	if err := e.v.Required(ctx, "period.startTime", input.Period.StartTime); err != nil {
		return err
	}
	if err := e.v.Required(ctx, "period.endTime", input.Period.EndTime); err != nil {
		return err
	}

	// Pass 2: Other validations
	if err := e.v.TimeBefore(ctx, "period.startTime", input.Period.StartTime, input.Period.EndTime); err != nil {
		return err
	}
	return nil
}

// handleGetTasks 封装了端点的自动化执行流
func (e *TaskCenterExecutor[T, C]) handleGetTasks(request C, info MethodInfo) {
	var input GetTasksInput
	if err := e.bindGetTasks(request, &input); err != nil {
		request.RenderJson(e.r.ErrorToStatus(request.Native(), err), e.r.BindResData(request.Native(), nil, err))
		return
	}
	result, err := e.biz.GetTasks(request.Context(), &input)
	if err != nil {
		request.RenderJson(e.r.ErrorToStatus(request.Native(), err), e.r.BindResData(request.Native(), nil, err))
		return
	}
	request.RenderJson(200, e.r.BindResData(request.Native(), result, nil))
}

// bindGetTasks 自动生成的参数提取与转换实现
func (e *TaskCenterExecutor[T, C]) bindGetTasks(request C, input *GetTasksInput) error {
	if val := request.GetQuery("page"); val != "" {
		if v, err := IntFromParam(val); err == nil {
			v2 := v
			input.Page = &v2
		} else {
			return err
		}
	}
	if val := request.GetQuery("size"); val != "" {
		if v, err := IntFromParam(val); err == nil {
			v2 := v
			input.Size = &v2
		} else {
			return err
		}
	}
	return nil
}
