// Code generated by github.com/xslasd/resgen. DO NOT EDIT.
// This file will be automatically regenerated based on the schema.

package resolver

import (
	"context"
	"time"
)

// ==========================================
// 1. Models
// ==========================================

// CreateTaskInput 输入模型
type CreateTaskInput struct {
	Title  string     `json:"title"`
	Period TaskPeriod `json:"period"`
}

// TaskPeriod 输入模型
type TaskPeriod struct {
	StartTime time.Time `json:"start_time"`
	EndTime   time.Time `json:"end_time"`
}

// GetTasksInput 输入模型
type GetTasksInput struct {
	Page *int `json:"page"`
	Size *int `json:"size"`
}

// ==========================================
// 2. Resolver Interface
// ==========================================

// TaskCenterResolver 定义模块业务逻辑接口
type TaskCenterResolver[T any] interface {

	// CreateTask POST /tasks/create
	CreateTask(ctx context.Context, input *CreateTaskInput) (*string, error)

	// GetTasks GET /tasks/list
	GetTasks(ctx context.Context, input *GetTasksInput) (*string, error)
}

// ==========================================
// 3. Executor / Binders
// ==========================================

/*
Resgen 自动化执行流说明:
1. Request Decorators  : 全局与特化请求拦截 (Auth, RateLimit 等)
2. Binding & Validation: 自动参数绑定与核心规则校验
3. Invoke Decorators   : 业务调用前的特化处理 (OwnerCheck 等)
4. Business Logic      : 调用 Resolver 接口实现的业务逻辑
5. Response Decorators : 结果脱敏或格式转换 (MaskEmail 等)
6. Result Response     : 最终结果渲染响应
*/

func MountTaskCenter[T any, C ServerContext[T]](en *Engine[C], biz TaskCenterResolver[T]) {
	d, _ := en.Decorator().(Decorator[T])
	v, _ := en.Validator().(Validator[T])
	r, _ := en.Responder().(Responder[T])
	executor := &TaskCenterExecutor[T, C]{
		en:  en,
		biz: biz,
		d:   d,
		v:   v,
		r:   r,
	}

	executor.mount()
}

// TaskCenterExecutor 模块执行器私有实现
type TaskCenterExecutor[T any, C ServerContext[T]] struct {
	en  *Engine[C]
	biz TaskCenterResolver[T]
	d   Decorator[T]
	v   Validator[T]
	r   Responder[T]
}

func (e *TaskCenterExecutor[T, C]) mount() {

	// --- 注册组: Tasks ---

	infoCreateTask := MethodInfo{
		Module: "TaskCenter",
		Group:  "/tasks",
		Method: "POST",
		Name:   "CreateTask",
		Path:   "/tasks/create",
	}
	e.en.Register(infoCreateTask, e.handleCreateTask)

	infoGetTasks := MethodInfo{
		Module: "TaskCenter",
		Group:  "/tasks",
		Method: "GET",
		Name:   "GetTasks",
		Path:   "/tasks/list",
	}
	e.en.Register(infoGetTasks, e.handleGetTasks)
}

// handleCreateTask 封装了端点的自动化执行流
func (e *TaskCenterExecutor[T, C]) handleCreateTask(request C, info MethodInfo) {
	ctx := request.Native()
	var input CreateTaskInput
	if err := e.bindCreateTask(request, &input); err != nil {
		request.RenderJson(e.r.ErrorToStatus(ctx, err), e.r.BindResData(ctx, nil, err))
		return
	}
	if err := e.validateCreateTask(ctx, &input); err != nil {
		request.RenderJson(e.r.ErrorToStatus(ctx, err), e.r.BindResData(ctx, nil, err))
		return
	}
	result, err := e.biz.CreateTask(request.Context(), &input)
	if err != nil {
		request.RenderJson(e.r.ErrorToStatus(ctx, err), e.r.BindResData(ctx, nil, err))
		return
	}
	request.RenderJson(200, e.r.BindResData(ctx, result, nil))
}

// bindCreateTask 自动生成的参数提取与转换实现
func (e *TaskCenterExecutor[T, C]) bindCreateTask(request C, input *CreateTaskInput) error {
	if err := request.Payload(SourceJson, input); err != nil {
		return err
	}
	return nil
}

// validateCreateTask 参数验证逻辑
func (e *TaskCenterExecutor[T, C]) validateCreateTask(ctx T, input *CreateTaskInput) error {
	// Pass 1: Required validations
	if err := e.v.Required(ctx, "title", input.Title); err != nil {
		return err
	}
	if err := e.v.Required(ctx, "period", input.Period); err != nil {
		return err
	}

	// Pass 2: Other validations
	return nil
}

// handleGetTasks 封装了端点的自动化执行流
func (e *TaskCenterExecutor[T, C]) handleGetTasks(request C, info MethodInfo) {
	ctx := request.Native()
	var input GetTasksInput
	if err := e.bindGetTasks(request, &input); err != nil {
		request.RenderJson(e.r.ErrorToStatus(ctx, err), e.r.BindResData(ctx, nil, err))
		return
	}
	result, err := e.biz.GetTasks(request.Context(), &input)
	if err != nil {
		request.RenderJson(e.r.ErrorToStatus(ctx, err), e.r.BindResData(ctx, nil, err))
		return
	}
	request.RenderJson(200, e.r.BindResData(ctx, result, nil))
}

// bindGetTasks 自动生成的参数提取与转换实现
func (e *TaskCenterExecutor[T, C]) bindGetTasks(request C, input *GetTasksInput) error {
	if err := request.Query("page", &input.Page); err != nil {
		return err
	}
	if err := request.Query("size", &input.Size); err != nil {
		return err
	}
	return nil
}
