// Code generated by github.com/xslasd/resgen v0.7.1. DO NOT EDIT.
// This file will be automatically regenerated based on the schema.

package resolver

import (
	"context"
	"fmt"
	"strconv"
)

// ==========================================
// 1. Enums
// ==========================================

// UnionKind 枚举类型
type UnionKind string

const (
	UnionKind_article UnionKind = "article"

	UnionKind_video UnionKind = "video"
)

// IsValid 检查枚举值是否合法
func (e UnionKind) IsValid() bool {
	switch e {
	case UnionKind_article, UnionKind_video:
		return true
	}
	return false
}

// FromParam 从字符串解析枚举 (用于 Query/Path/Header 参数)
func (e *UnionKind) FromParam(ctx any, s string) error {
	switch s {
	case "article":
		*e = UnionKind_article
		return nil
	case "video":
		*e = UnionKind_video
		return nil
	}
	return &InvalidEnumError{
		EnumType: "UnionKind",
		Value:    s,
	}
}

// ==========================================
// 2. Models
// ==========================================

// UnionArticle 输出模型
type UnionArticle struct {
	Title   string `json:"title"`
	Content string `json:"content"`
}

// UnionVideo 输出模型
type UnionVideo struct {
	Title    string `json:"title"`
	URL      string `json:"url"`
	Duration int    `json:"duration"`
}

// CreatePostInput 输入模型
type CreatePostInput struct {
	Type    UnionKind `json:"type"`
	Payload any       `json:"payload"`
}

// ResolveUnions 递归解析模型 CreatePostInput 及其子字段中的所有多态 Union 字段
func (m *CreatePostInput) ResolveUnions() error {
	if m == nil {
		return nil
	}
	if StringifyUnionDiscriminator(m.Type) != "" && m.Payload != nil {
		resolved, err := ResolveContentPayload(m.Type, m.Payload)
		if err != nil {
			return fmt.Errorf("多态 payload 解析失败: %w", err)
		}
		m.Payload = resolved
	}
	return nil
}

// ContentPostItem 输出模型
type ContentPostItem struct {
	ID      int       `json:"id"`
	Type    UnionKind `json:"type"`
	Payload any       `json:"payload"`
}

// ResolveUnions 递归解析模型 ContentPostItem 及其子字段中的所有多态 Union 字段
func (m *ContentPostItem) ResolveUnions() error {
	if m == nil {
		return nil
	}
	if StringifyUnionDiscriminator(m.Type) != "" && m.Payload != nil {
		resolved, err := ResolveContentPayload(m.Type, m.Payload)
		if err != nil {
			return fmt.Errorf("多态 payload 解析失败: %w", err)
		}
		m.Payload = resolved
	}
	return nil
}

// PostDetailInput 输入模型
type PostDetailInput struct {
	Author  string    `json:"author"`
	Type    UnionKind `json:"type"`
	Payload any       `json:"payload"`
}

// ResolveUnions 递归解析模型 PostDetailInput 及其子字段中的所有多态 Union 字段
func (m *PostDetailInput) ResolveUnions() error {
	if m == nil {
		return nil
	}
	if StringifyUnionDiscriminator(m.Type) != "" && m.Payload != nil {
		resolved, err := ResolveContentPayload(m.Type, m.Payload)
		if err != nil {
			return fmt.Errorf("多态 payload 解析失败: %w", err)
		}
		m.Payload = resolved
	}
	return nil
}

// BatchCreatePostInput 输入模型
type BatchCreatePostInput struct {
	BatchName  string            `json:"batch_name"`
	PinnedPost *PostDetailInput  `json:"pinned_post"`
	Items      []PostDetailInput `json:"items"`
}

// ResolveUnions 递归解析模型 BatchCreatePostInput 及其子字段中的所有多态 Union 字段
func (m *BatchCreatePostInput) ResolveUnions() error {
	if m == nil {
		return nil
	}
	if m.PinnedPost != nil {
		if err := m.PinnedPost.ResolveUnions(); err != nil {
			return fmt.Errorf("%s: %w", "pinnedPost", err)
		}
	}
	for i := range m.Items {
		if err := m.Items[i].ResolveUnions(); err != nil {
			return fmt.Errorf("%s[%d]: %w", "items", i, err)
		}
	}
	return nil
}

// BatchCreatePostResult 输出模型
type BatchCreatePostResult struct {
	BatchName string            `json:"batch_name"`
	Total     int               `json:"total"`
	Items     []ContentPostItem `json:"items"`
}

// ResolveUnions 递归解析模型 BatchCreatePostResult 及其子字段中的所有多态 Union 字段
func (m *BatchCreatePostResult) ResolveUnions() error {
	if m == nil {
		return nil
	}
	for i := range m.Items {
		if err := m.Items[i].ResolveUnions(); err != nil {
			return fmt.Errorf("%s[%d]: %w", "items", i, err)
		}
	}
	return nil
}

// ==========================================
// 2. Resolver Interface
// ==========================================

// UnionDemoResolver 定义模块业务逻辑接口
type UnionDemoResolver[T any] interface {

	// GetPost GET /posts/:id
	GetPost(ctx context.Context, id *int) (*ContentPostItem, error)

	// CreatePost POST /posts/
	CreatePost(ctx context.Context, input *CreatePostInput) (*ContentPostItem, error)

	// BatchCreatePost POST /posts/batch
	BatchCreatePost(ctx context.Context, input *BatchCreatePostInput) (*BatchCreatePostResult, error)
}

// ==========================================
// 3. Executor / Binders
// ==========================================

/*
Resgen 自动化执行流说明:
1. Request Decorators  : 全局与特化请求拦截 (Auth, RateLimit 等)
2. Binding & Validation: 自动参数绑定与核心规则校验
3. Invoke Decorators   : 业务调用前的特化处理 (OwnerCheck 等)
4. Business Logic      : 调用 Resolver 接口实现的业务逻辑
5. Response Decorators : 结果脱敏或格式转换 (MaskEmail 等)
6. Result Response     : 最终结果渲染响应
*/

func MountUnionDemo[T any, C ServerContext[T]](en *Engine[C], biz UnionDemoResolver[T]) {
	d, _ := en.Decorator().(Decorator[T])
	v, _ := en.Validator().(Validator[T])
	r, _ := en.Responder().(Responder[T])
	executor := &UnionDemoExecutor[T, C]{
		en:  en,
		biz: biz,
		d:   d,
		v:   v,
		r:   r,
	}

	executor.mount()
}

type UnionDemoExecutor[T any, C ServerContext[T]] struct {
	en  *Engine[C]
	biz UnionDemoResolver[T]
	d   Decorator[T]
	v   Validator[T]
	r   Responder[T]
}

func (e *UnionDemoExecutor[T, C]) mount() {

	// --- 注册组: Posts ---

	infoGetPost := MethodInfo{
		Module: "UnionDemo",
		Group:  "/posts",
		Method: "GET",
		Name:   "GetPost",
		Path:   "/posts/:id",
	}
	e.register(infoGetPost, e.handleGetPost)

	infoCreatePost := MethodInfo{
		Module: "UnionDemo",
		Group:  "/posts",
		Method: "POST",
		Name:   "CreatePost",
		Path:   "/posts/",
	}
	e.register(infoCreatePost, e.handleCreatePost)

	infoBatchCreatePost := MethodInfo{
		Module: "UnionDemo",
		Group:  "/posts",
		Method: "POST",
		Name:   "BatchCreatePost",
		Path:   "/posts/batch",
	}
	e.register(infoBatchCreatePost, e.handleBatchCreatePost)
}

func (e *UnionDemoExecutor[T, C]) register(info MethodInfo, handler HandlerFunc[C]) {
	info.HandlerPos = GetHandlerJumpPath(e.biz, info.Name)
	e.en.Register(info, handler)
}

// handleGetPost 封装了端点的自动化执行流
func (e *UnionDemoExecutor[T, C]) handleGetPost(request C, info MethodInfo) {
	native := request.Native()
	var IDVal *int

	if val := request.GetPath("id"); val != "" {
		if v, err := IntFromParam(val); err == nil {
			v2 := v
			IDVal = &v2
		} else {
			request.RenderJson(e.r.ErrorToStatus(native, err), e.r.BindResData(native, nil, err))
			return
		}
	}
	result, err := e.biz.GetPost(request.Context(), IDVal)
	if err != nil {
		request.RenderJson(e.r.ErrorToStatus(native, err), e.r.BindResData(native, nil, err))
		return
	}
	request.RenderJson(200, e.r.BindResData(native, result, nil))
}

// handleCreatePost 封装了端点的自动化执行流
func (e *UnionDemoExecutor[T, C]) handleCreatePost(request C, info MethodInfo) {
	native := request.Native()
	var input CreatePostInput
	if err := e.bindCreatePost(request, &input); err != nil {
		request.RenderJson(e.r.ErrorToStatus(native, err), e.r.BindResData(native, nil, err))
		return
	}
	if err := e.validateCreatePost(native, &input); err != nil {
		request.RenderJson(e.r.ErrorToStatus(native, err), e.r.BindResData(native, nil, err))
		return
	}
	result, err := e.biz.CreatePost(request.Context(), &input)
	if err != nil {
		request.RenderJson(e.r.ErrorToStatus(native, err), e.r.BindResData(native, nil, err))
		return
	}
	request.RenderJson(200, e.r.BindResData(native, result, nil))
}

// bindCreatePost 自动生成的参数提取与转换实现
func (e *UnionDemoExecutor[T, C]) bindCreatePost(request C, input *CreatePostInput) error {
	if err := request.Payload(SourceJSON, input); err != nil {
		return err
	}
	// 递归处理多态 Union 字段 (支持多级嵌套与切片自动递归)
	if err := input.ResolveUnions(); err != nil {
		return err
	}
	return nil
}

// validateCreatePost 参数验证逻辑
func (e *UnionDemoExecutor[T, C]) validateCreatePost(ctx T, input *CreatePostInput) error {
	if err := e.v.Required(ctx, "type", input.Type); err != nil {
		return err
	}
	if !(input.Type).IsValid() {
		return e.v.EnumError(ctx, "type", "UnionKind", input.Type)
	}

	return nil
}

// handleBatchCreatePost 封装了端点的自动化执行流
func (e *UnionDemoExecutor[T, C]) handleBatchCreatePost(request C, info MethodInfo) {
	native := request.Native()
	var input BatchCreatePostInput
	if err := e.bindBatchCreatePost(request, &input); err != nil {
		request.RenderJson(e.r.ErrorToStatus(native, err), e.r.BindResData(native, nil, err))
		return
	}
	if err := e.validateBatchCreatePost(native, &input); err != nil {
		request.RenderJson(e.r.ErrorToStatus(native, err), e.r.BindResData(native, nil, err))
		return
	}
	result, err := e.biz.BatchCreatePost(request.Context(), &input)
	if err != nil {
		request.RenderJson(e.r.ErrorToStatus(native, err), e.r.BindResData(native, nil, err))
		return
	}
	request.RenderJson(200, e.r.BindResData(native, result, nil))
}

// bindBatchCreatePost 自动生成的参数提取与转换实现
func (e *UnionDemoExecutor[T, C]) bindBatchCreatePost(request C, input *BatchCreatePostInput) error {
	if err := request.Payload(SourceJSON, input); err != nil {
		return err
	}
	// 递归处理多态 Union 字段 (支持多级嵌套与切片自动递归)
	if err := input.ResolveUnions(); err != nil {
		return err
	}
	return nil
}

// validateBatchCreatePost 参数验证逻辑
func (e *UnionDemoExecutor[T, C]) validateBatchCreatePost(ctx T, input *BatchCreatePostInput) error {
	if err := e.v.Required(ctx, "batchName", input.BatchName); err != nil {
		return err
	}
	if input.PinnedPost != nil {
		if err := e.v.Required(ctx, "pinnedPost"+".author", input.PinnedPost.Author); err != nil {
			return err
		}
		if err := e.v.Required(ctx, "pinnedPost"+".type", input.PinnedPost.Type); err != nil {
			return err
		}
		if !(input.PinnedPost.Type).IsValid() {
			return e.v.EnumError(ctx, "pinnedPost"+".type", "UnionKind", input.PinnedPost.Type)
		}
	}
	for i, item := range input.Items {
		if err := e.v.Required(ctx, "items"+"["+strconv.Itoa(i)+"]", item); err != nil {
			return err
		}
		if err := e.v.Required(ctx, "items"+"["+strconv.Itoa(i)+"]"+".author", item.Author); err != nil {
			return err
		}
		if err := e.v.Required(ctx, "items"+"["+strconv.Itoa(i)+"]"+".type", item.Type); err != nil {
			return err
		}
		if !(item.Type).IsValid() {
			return e.v.EnumError(ctx, "items"+"["+strconv.Itoa(i)+"]"+".type", "UnionKind", item.Type)
		}
	}

	return nil
}
