// Code generated by github.com/xslasd/resgen. DO NOT EDIT.
// This file will be automatically regenerated based on the schema.

package resolver

import (
	"context"
	"mime/multipart"
	"time"
)

// ==========================================
// 1. Models
// ==========================================

// User 输出模型
type User struct {
	Id        int        `json:"id"`
	Username  string     `json:"username"`
	Email     string     `json:"email"`
	AvatarUrl *string    `json:"avatar_url"`
	CreatedAt *time.Time `json:"created_at"`
}

// CreateUserInput 输入模型
type CreateUserInput struct {
	Username        string `json:"username"`
	Email           string `json:"email"`
	Mobile          string `json:"mobile"`
	Password        string `json:"password"`
	ConfirmPassword string `json:"confirm_password"`
}

// UploadAvatarInput 输入模型
type UploadAvatarInput struct {
	Id   int                   `json:"id"`
	File *multipart.FileHeader `json:"file"`
}

// ProfileUpdateInput 输入模型
type ProfileUpdateInput struct {
	CurrentEmail string       `json:"current_email"`
	Security     SecurityInfo `json:"security"`
	EmailConfirm string       `json:"email_confirm"`
}

// SecurityInfo 输出模型
type SecurityInfo struct {
	BackupEmail string `json:"backup_email"`
}

// ValidGET 输入模型
type ValidGET struct {
	Page *int `json:"page"`
	Size *int `json:"size"`
}

// Token 输出模型
type Token struct {
	Token string `json:"token"`
}

// UserCopyArgs 输入模型
type UserCopyArgs struct {
	Id string `json:"id"`
}

// LoginArgs 输入模型
type LoginArgs struct {
	Username *string `json:"username"`
	Password *string `json:"password"`
}

// UpdateUserArgs 输入模型
type UpdateUserArgs struct {
	Id    int     `json:"id"`
	Email *string `json:"email"`
}

// GetUsersArgs 输入模型
type GetUsersArgs struct {
	Page int  `json:"page"`
	Size *int `json:"size"`
}

// GetUserArgs 输入模型
type GetUserArgs struct {
	Id *int `json:"id"`
}

// DeleteUserArgs 输入模型
type DeleteUserArgs struct {
	Id *int `json:"id"`
}

// ==========================================
// 2. Resolver Interface
// ==========================================

// UserCenterResolver 定义模块业务逻辑接口
type UserCenterResolver[T any] interface {

	// GetProfile GET /users/profile
	GetProfile(ctx context.Context) (*User, error)

	// UserCopy GET /users/user/copy
	UserCopy(ctx context.Context, input *UserCopyArgs) (*User, error)

	// CreateUser POST /users/register
	CreateUser(ctx context.Context, input *CreateUserInput) (*User, error)

	BindLogin(request ServerContextBase, input *LoginArgs) error
	ValidateLogin(ctx T, input *LoginArgs) error
	// Login POST /users/login
	Login(ctx context.Context, input *LoginArgs) (*Token, error)

	OnInvoke_CheckOwner_UpdateUser(ctx T, info MethodInfo, input *UpdateUserArgs) error
	// UpdateUser POST /users/update
	UpdateUser(ctx context.Context, input *UpdateUserArgs) (*User, error)
	OnResponse_MaskEmail_UpdateUser(ctx T, info MethodInfo, input *UpdateUserArgs, result *User, err error) (*User, error)

	// UploadAvatar POST /users/avatar
	UploadAvatar(ctx context.Context, input *UploadAvatarInput) (*string, error)

	// GetUsers GET /users/users
	GetUsers(ctx context.Context, input *GetUsersArgs) (*[]*User, error)

	// GetUser GET /users/users/:id
	GetUser(ctx context.Context, input *GetUserArgs) (*User, error)

	// DeleteUser DELETE /users/users/:id
	DeleteUser(ctx context.Context, input *DeleteUserArgs) (*string, error)

	// UpdateProfile POST /users/update_profile
	UpdateProfile(ctx context.Context, input *ProfileUpdateInput) (*string, error)

	// ExportUsers GET /users/export
	ExportUsers(ctx context.Context) (*string, error)

	// TestValid GET /users/test_valid
	TestValid(ctx context.Context, input *ValidGET) (any, error)
}

// ==========================================
// 3. Executor / Binders
// ==========================================

/*
Resgen 自动化执行流说明:
1. Request Decorators  : 全局与特化请求拦截 (Auth, RateLimit 等)
2. Binding & Validation: 自动参数绑定与核心规则校验
3. Invoke Decorators   : 业务调用前的特化处理 (OwnerCheck 等)
4. Business Logic      : 调用 Resolver 接口实现的业务逻辑
5. Response Decorators : 结果脱敏或格式转换 (MaskEmail 等)
6. Result Response     : 最终结果渲染响应
*/

func MountUserCenter[T any, C ServerContext[T]](en *Engine[C], biz UserCenterResolver[T]) {
	d, _ := en.Decorator().(Decorator[T])
	v, _ := en.Validator().(Validator[T])
	r, _ := en.Responder().(Responder[T])
	executor := &UserCenterExecutor[T, C]{
		en:  en,
		biz: biz,
		d:   d,
		v:   v,
		r:   r,
	}

	executor.mount()
}

// UserCenterExecutor 模块执行器私有实现
type UserCenterExecutor[T any, C ServerContext[T]] struct {
	en  *Engine[C]
	biz UserCenterResolver[T]
	d   Decorator[T]
	v   Validator[T]
	r   Responder[T]
}

func (e *UserCenterExecutor[T, C]) mount() {

	// --- 注册组: Users ---

	infoGetProfile := MethodInfo{
		Module: "UserCenter",
		Group:  "/users",
		Method: "GET",
		Name:   "GetProfile",
		Path:   "/users/profile",
	}
	e.en.Register(infoGetProfile, e.handleGetProfile)

	infoUserCopy := MethodInfo{
		Module: "UserCenter",
		Group:  "/users",
		Method: "GET",
		Name:   "UserCopy",
		Path:   "/users/user/copy",
	}
	e.en.Register(infoUserCopy, e.handleUserCopy)

	infoCreateUser := MethodInfo{
		Module: "UserCenter",
		Group:  "/users",
		Method: "POST",
		Name:   "CreateUser",
		Path:   "/users/register",
	}
	e.en.Register(infoCreateUser, e.handleCreateUser)

	infoLogin := MethodInfo{
		Module: "UserCenter",
		Group:  "/users",
		Method: "POST",
		Name:   "Login",
		Path:   "/users/login",
	}
	e.en.Register(infoLogin, e.handleLogin)

	infoUpdateUser := MethodInfo{
		Module: "UserCenter",
		Group:  "/users",
		Method: "POST",
		Name:   "UpdateUser",
		Path:   "/users/update",
	}
	e.en.Register(infoUpdateUser, e.handleUpdateUser)

	infoUploadAvatar := MethodInfo{
		Module: "UserCenter",
		Group:  "/users",
		Method: "POST",
		Name:   "UploadAvatar",
		Path:   "/users/avatar",
	}
	e.en.Register(infoUploadAvatar, e.handleUploadAvatar)

	infoGetUsers := MethodInfo{
		Module: "UserCenter",
		Group:  "/users",
		Method: "GET",
		Name:   "GetUsers",
		Path:   "/users/users",
	}
	e.en.Register(infoGetUsers, e.handleGetUsers)

	infoGetUser := MethodInfo{
		Module: "UserCenter",
		Group:  "/users",
		Method: "GET",
		Name:   "GetUser",
		Path:   "/users/users/:id",
	}
	e.en.Register(infoGetUser, e.handleGetUser)

	infoDeleteUser := MethodInfo{
		Module: "UserCenter",
		Group:  "/users",
		Method: "DELETE",
		Name:   "DeleteUser",
		Path:   "/users/users/:id",
	}
	e.en.Register(infoDeleteUser, e.handleDeleteUser)

	infoUpdateProfile := MethodInfo{
		Module: "UserCenter",
		Group:  "/users",
		Method: "POST",
		Name:   "UpdateProfile",
		Path:   "/users/update_profile",
	}
	e.en.Register(infoUpdateProfile, e.handleUpdateProfile)

	infoExportUsers := MethodInfo{
		Module: "UserCenter",
		Group:  "/users",
		Method: "GET",
		Name:   "ExportUsers",
		Path:   "/users/export",
	}
	e.en.Register(infoExportUsers, e.handleExportUsers)

	infoTestValid := MethodInfo{
		Module: "UserCenter",
		Group:  "/users",
		Method: "GET",
		Name:   "TestValid",
		Path:   "/users/test_valid",
	}
	e.en.Register(infoTestValid, e.handleTestValid)
}

// handleGetProfile 封装了端点的自动化执行流
func (e *UserCenterExecutor[T, C]) handleGetProfile(request C, info MethodInfo) {
	ctx := request.Native()
	if err := e.d.LoginRequired(ctx, info); err != nil {
		request.RenderJson(e.r.ErrorToStatus(ctx, err), e.r.BindResData(ctx, nil, err))
		return
	}
	result, err := e.biz.GetProfile(request.Context())
	if err != nil {
		request.RenderJson(e.r.ErrorToStatus(ctx, err), e.r.BindResData(ctx, nil, err))
		return
	}
	request.RenderJson(200, e.r.BindResData(ctx, result, nil))
}

// handleUserCopy 封装了端点的自动化执行流
func (e *UserCenterExecutor[T, C]) handleUserCopy(request C, info MethodInfo) {
	ctx := request.Native()
	var input UserCopyArgs
	if err := e.bindUserCopy(request, &input); err != nil {
		request.RenderJson(e.r.ErrorToStatus(ctx, err), e.r.BindResData(ctx, nil, err))
		return
	}
	if err := e.validateUserCopy(ctx, &input); err != nil {
		request.RenderJson(e.r.ErrorToStatus(ctx, err), e.r.BindResData(ctx, nil, err))
		return
	}
	result, err := e.biz.UserCopy(request.Context(), &input)
	if err != nil {
		request.RenderJson(e.r.ErrorToStatus(ctx, err), e.r.BindResData(ctx, nil, err))
		return
	}
	request.RenderJson(200, e.r.BindResData(ctx, result, nil))
}

// bindUserCopy 自动生成的参数提取与转换实现
func (e *UserCenterExecutor[T, C]) bindUserCopy(request C, input *UserCopyArgs) error {

	if err := request.Field(SourceJson, "id", &input.Id); err != nil {
		return err
	}

	return nil
}

// validateUserCopy 参数验证逻辑
func (e *UserCenterExecutor[T, C]) validateUserCopy(ctx T, input *UserCopyArgs) error {
	// Pass 1: Required validations for top-level arguments and their fields
	if err := e.v.Required(ctx, "id", input.Id); err != nil {
		return err
	}

	// Pass 2: Other validations
	return nil
}

// handleCreateUser 封装了端点的自动化执行流
func (e *UserCenterExecutor[T, C]) handleCreateUser(request C, info MethodInfo) {
	ctx := request.Native()
	var input CreateUserInput
	if err := e.bindCreateUser(request, &input); err != nil {
		request.RenderJson(e.r.ErrorToStatus(ctx, err), e.r.BindResData(ctx, nil, err))
		return
	}
	if err := e.validateCreateUser(ctx, &input); err != nil {
		request.RenderJson(e.r.ErrorToStatus(ctx, err), e.r.BindResData(ctx, nil, err))
		return
	}
	result, err := e.biz.CreateUser(request.Context(), &input)
	if err != nil {
		request.RenderJson(e.r.ErrorToStatus(ctx, err), e.r.BindResData(ctx, nil, err))
		return
	}
	request.RenderJson(200, e.r.BindResData(ctx, result, nil))
}

// bindCreateUser 自动生成的参数提取与转换实现
func (e *UserCenterExecutor[T, C]) bindCreateUser(request C, input *CreateUserInput) error {
	if err := request.Payload(SourceForm, input); err != nil {
		return err
	}
	return nil
}

// validateCreateUser 参数验证逻辑
func (e *UserCenterExecutor[T, C]) validateCreateUser(ctx T, input *CreateUserInput) error {
	// Pass 1: Required validations
	if err := e.v.Required(ctx, "username", input.Username); err != nil {
		return err
	}
	if err := e.v.Required(ctx, "email", input.Email); err != nil {
		return err
	}
	if err := e.v.Required(ctx, "mobile", input.Mobile); err != nil {
		return err
	}
	if err := e.v.Required(ctx, "password", input.Password); err != nil {
		return err
	}
	if err := e.v.Required(ctx, "confirmPassword", input.ConfirmPassword); err != nil {
		return err
	}

	// Pass 2: Other validations
	if err := e.v.Min(ctx, "username", input.Username, 5); err != nil {
		return err
	}
	if err := e.v.Max(ctx, "username", input.Username, 20); err != nil {
		return err
	}
	if err := e.v.Email(ctx, "email", input.Email); err != nil {
		return err
	}
	if err := e.v.Mobile(ctx, "mobile", input.Mobile); err != nil {
		return err
	}
	return nil
}

// handleLogin 封装了端点的自动化执行流
func (e *UserCenterExecutor[T, C]) handleLogin(request C, info MethodInfo) {
	ctx := request.Native()
	var input LoginArgs
	if err := e.biz.BindLogin(request, &input); err != nil {
		request.RenderJson(e.r.ErrorToStatus(ctx, err), e.r.BindResData(ctx, nil, err))
		return
	}
	if err := e.biz.ValidateLogin(ctx, &input); err != nil {
		request.RenderJson(e.r.ErrorToStatus(ctx, err), e.r.BindResData(ctx, nil, err))
		return
	}
	result, err := e.biz.Login(request.Context(), &input)
	if err != nil {
		request.RenderJson(e.r.ErrorToStatus(ctx, err), e.r.BindResData(ctx, nil, err))
		return
	}
	request.RenderJson(201, e.r.BindResData(ctx, result, nil))
}

// handleUpdateUser 封装了端点的自动化执行流
func (e *UserCenterExecutor[T, C]) handleUpdateUser(request C, info MethodInfo) {
	ctx := request.Native()
	if err := e.d.LoginRequired(ctx, info); err != nil {
		request.RenderJson(e.r.ErrorToStatus(ctx, err), e.r.BindResData(ctx, nil, err))
		return
	}
	var input UpdateUserArgs
	if err := e.bindUpdateUser(request, &input); err != nil {
		request.RenderJson(e.r.ErrorToStatus(ctx, err), e.r.BindResData(ctx, nil, err))
		return
	}
	if err := e.validateUpdateUser(ctx, &input); err != nil {
		request.RenderJson(e.r.ErrorToStatus(ctx, err), e.r.BindResData(ctx, nil, err))
		return
	}
	if err := e.biz.OnInvoke_CheckOwner_UpdateUser(ctx, info, &input); err != nil {
		request.RenderJson(e.r.ErrorToStatus(ctx, err), e.r.BindResData(ctx, nil, err))
		return
	}
	result, err := e.biz.UpdateUser(request.Context(), &input)
	if res, rerr := e.biz.OnResponse_MaskEmail_UpdateUser(ctx, info, &input, result, err); rerr != nil {
		request.RenderJson(e.r.ErrorToStatus(ctx, rerr), e.r.BindResData(ctx, nil, rerr))
		return
	} else {
		result = res
		err = rerr
	}
	if err != nil {
		request.RenderJson(e.r.ErrorToStatus(ctx, err), e.r.BindResData(ctx, nil, err))
		return
	}
	request.RenderJson(200, e.r.BindResData(ctx, result, nil))
}

// bindUpdateUser 自动生成的参数提取与转换实现
func (e *UserCenterExecutor[T, C]) bindUpdateUser(request C, input *UpdateUserArgs) error {
	if err := request.Payload(SourceJson, input); err != nil {
		return err
	}

	if err := request.Field(SourceJson, "id", &input.Id); err != nil {
		return err
	}

	if err := request.Field(SourceJson, "email", &input.Email); err != nil {
		return err
	}

	return nil
}

// validateUpdateUser 参数验证逻辑
func (e *UserCenterExecutor[T, C]) validateUpdateUser(ctx T, input *UpdateUserArgs) error {
	// Pass 1: Required validations for top-level arguments and their fields
	if err := e.v.Required(ctx, "id", input.Id); err != nil {
		return err
	}

	// Pass 2: Other validations
	return nil
}

// handleUploadAvatar 封装了端点的自动化执行流
func (e *UserCenterExecutor[T, C]) handleUploadAvatar(request C, info MethodInfo) {
	ctx := request.Native()
	var input UploadAvatarInput
	if err := e.bindUploadAvatar(request, &input); err != nil {
		request.RenderJson(e.r.ErrorToStatus(ctx, err), e.r.BindResData(ctx, nil, err))
		return
	}
	if err := e.validateUploadAvatar(ctx, &input); err != nil {
		request.RenderJson(e.r.ErrorToStatus(ctx, err), e.r.BindResData(ctx, nil, err))
		return
	}
	result, err := e.biz.UploadAvatar(request.Context(), &input)
	if err != nil {
		request.RenderJson(e.r.ErrorToStatus(ctx, err), e.r.BindResData(ctx, nil, err))
		return
	}
	request.RenderJson(200, e.r.BindResData(ctx, result, nil))
}

// bindUploadAvatar 自动生成的参数提取与转换实现
func (e *UserCenterExecutor[T, C]) bindUploadAvatar(request C, input *UploadAvatarInput) error {
	if err := request.Payload(SourceMultipart, input); err != nil {
		return err
	}
	return nil
}

// validateUploadAvatar 参数验证逻辑
func (e *UserCenterExecutor[T, C]) validateUploadAvatar(ctx T, input *UploadAvatarInput) error {
	// Pass 1: Required validations
	if err := e.v.Required(ctx, "id", input.Id); err != nil {
		return err
	}
	if err := e.v.Required(ctx, "file", input.File); err != nil {
		return err
	}

	// Pass 2: Other validations
	if input.File != nil {
		if err := e.v.FileRule(ctx, "file", *input.File, 2097152, []string{"image/jpeg", "image/png"}, "头像格式错误或文件太大"); err != nil {
			return err
		}
	}
	return nil
}

// handleGetUsers 封装了端点的自动化执行流
func (e *UserCenterExecutor[T, C]) handleGetUsers(request C, info MethodInfo) {
	ctx := request.Native()
	var input GetUsersArgs
	if err := e.bindGetUsers(request, &input); err != nil {
		request.RenderJson(e.r.ErrorToStatus(ctx, err), e.r.BindResData(ctx, nil, err))
		return
	}
	if err := e.validateGetUsers(ctx, &input); err != nil {
		request.RenderJson(e.r.ErrorToStatus(ctx, err), e.r.BindResData(ctx, nil, err))
		return
	}
	result, err := e.biz.GetUsers(request.Context(), &input)
	if err != nil {
		request.RenderJson(e.r.ErrorToStatus(ctx, err), e.r.BindResData(ctx, nil, err))
		return
	}
	request.RenderJson(200, e.r.BindResData(ctx, result, nil))
}

// bindGetUsers 自动生成的参数提取与转换实现
func (e *UserCenterExecutor[T, C]) bindGetUsers(request C, input *GetUsersArgs) error {

	if err := request.Query("page", &input.Page); err != nil {
		return err
	}

	if err := request.Query("size", &input.Size); err != nil {
		return err
	}

	return nil
}

// validateGetUsers 参数验证逻辑
func (e *UserCenterExecutor[T, C]) validateGetUsers(ctx T, input *GetUsersArgs) error {
	// Pass 1: Required validations for top-level arguments and their fields
	if err := e.v.Required(ctx, "page", input.Page); err != nil {
		return err
	}

	// Pass 2: Other validations
	if err := e.v.Max(ctx, "size", input.Size, 100); err != nil {
		return err
	}
	return nil
}

// handleGetUser 封装了端点的自动化执行流
func (e *UserCenterExecutor[T, C]) handleGetUser(request C, info MethodInfo) {
	ctx := request.Native()
	var input GetUserArgs
	if err := e.bindGetUser(request, &input); err != nil {
		request.RenderJson(e.r.ErrorToStatus(ctx, err), e.r.BindResData(ctx, nil, err))
		return
	}
	result, err := e.biz.GetUser(request.Context(), &input)
	if err != nil {
		request.RenderJson(e.r.ErrorToStatus(ctx, err), e.r.BindResData(ctx, nil, err))
		return
	}
	request.RenderJson(200, result)
}

// bindGetUser 自动生成的参数提取与转换实现
func (e *UserCenterExecutor[T, C]) bindGetUser(request C, input *GetUserArgs) error {

	if err := request.Path("id", &input.Id); err != nil {
		return err
	}

	return nil
}

// handleDeleteUser 封装了端点的自动化执行流
func (e *UserCenterExecutor[T, C]) handleDeleteUser(request C, info MethodInfo) {
	ctx := request.Native()
	var input DeleteUserArgs
	if err := e.bindDeleteUser(request, &input); err != nil {
		request.RenderJson(e.r.ErrorToStatus(ctx, err), e.r.BindResData(ctx, nil, err))
		return
	}
	result, err := e.biz.DeleteUser(request.Context(), &input)
	if err != nil {
		request.RenderJson(e.r.ErrorToStatus(ctx, err), e.r.BindResData(ctx, nil, err))
		return
	}
	request.RenderJson(200, e.r.BindResData(ctx, result, nil))
}

// bindDeleteUser 自动生成的参数提取与转换实现
func (e *UserCenterExecutor[T, C]) bindDeleteUser(request C, input *DeleteUserArgs) error {

	if err := request.Path("id", &input.Id); err != nil {
		return err
	}

	return nil
}

// handleUpdateProfile 封装了端点的自动化执行流
func (e *UserCenterExecutor[T, C]) handleUpdateProfile(request C, info MethodInfo) {
	ctx := request.Native()
	var input ProfileUpdateInput
	if err := e.bindUpdateProfile(request, &input); err != nil {
		request.RenderJson(e.r.ErrorToStatus(ctx, err), e.r.BindResData(ctx, nil, err))
		return
	}
	if err := e.validateUpdateProfile(ctx, &input); err != nil {
		request.RenderJson(e.r.ErrorToStatus(ctx, err), e.r.BindResData(ctx, nil, err))
		return
	}
	result, err := e.biz.UpdateProfile(request.Context(), &input)
	if err != nil {
		request.RenderJson(e.r.ErrorToStatus(ctx, err), e.r.BindResData(ctx, nil, err))
		return
	}
	request.RenderJson(200, e.r.BindResData(ctx, result, nil))
}

// bindUpdateProfile 自动生成的参数提取与转换实现
func (e *UserCenterExecutor[T, C]) bindUpdateProfile(request C, input *ProfileUpdateInput) error {
	if err := request.Payload(SourceJson, input); err != nil {
		return err
	}
	return nil
}

// validateUpdateProfile 参数验证逻辑
func (e *UserCenterExecutor[T, C]) validateUpdateProfile(ctx T, input *ProfileUpdateInput) error {
	// Pass 1: Required validations
	if err := e.v.Required(ctx, "currentEmail", input.CurrentEmail); err != nil {
		return err
	}
	if err := e.v.Required(ctx, "security", input.Security); err != nil {
		return err
	}
	if err := e.v.Required(ctx, "emailConfirm", input.EmailConfirm); err != nil {
		return err
	}

	// Pass 2: Other validations
	if err := e.v.Email(ctx, "currentEmail", input.CurrentEmail); err != nil {
		return err
	}
	if err := e.v.Email(ctx, "emailConfirm", input.EmailConfirm); err != nil {
		return err
	}
	return nil
}

// handleExportUsers 封装了端点的自动化执行流
func (e *UserCenterExecutor[T, C]) handleExportUsers(request C, info MethodInfo) {
	ctx := request.Native()
	result, err := e.biz.ExportUsers(request.Context())
	if err != nil {
		request.RenderJson(e.r.ErrorToStatus(ctx, err), e.r.BindResData(ctx, nil, err))
		return
	}
	request.RenderText(200, result)
}

// handleTestValid 封装了端点的自动化执行流
func (e *UserCenterExecutor[T, C]) handleTestValid(request C, info MethodInfo) {
	ctx := request.Native()
	var input ValidGET
	if err := e.bindTestValid(request, &input); err != nil {
		request.RenderJson(e.r.ErrorToStatus(ctx, err), e.r.BindResData(ctx, nil, err))
		return
	}
	result, err := e.biz.TestValid(request.Context(), &input)
	if err != nil {
		request.RenderJson(e.r.ErrorToStatus(ctx, err), e.r.BindResData(ctx, nil, err))
		return
	}
	request.RenderJson(200, result)
}

// bindTestValid 自动生成的参数提取与转换实现
func (e *UserCenterExecutor[T, C]) bindTestValid(request C, input *ValidGET) error {
	if err := request.Query("page", &input.Page); err != nil {
		return err
	}
	if err := request.Query("size", &input.Size); err != nil {
		return err
	}
	return nil
}
