// Code generated by github.com/xslasd/resgen v0.3.3. DO NOT EDIT.
// This file will be automatically regenerated based on the schema.

package resolver

import (
	"context"
)

// ==========================================
// 1. Models
// ==========================================

// Article 输出模型
type Article struct {
	Id      int    `json:"id"`
	Title   string `json:"title"`
	Content string `json:"content"`
}

// PageResult 输出模型
type PageResult[T any] struct {
	List  T   `json:"list"`
	Total int `json:"total"`
	Page  int `json:"page"`
	Size  int `json:"size"`
}

// ListArticlesArgs 输入模型
type ListArticlesArgs struct {
	Page *int `json:"page"`
	Size *int `json:"size"`
}

// ListArticlesV2Args 输入模型
type ListArticlesV2Args struct {
	Page *int `json:"page"`
	Size *int `json:"size"`
}

// CreateArticleArgs 输入模型
type CreateArticleArgs struct {
	Title   string `json:"title"`
	Content string `json:"content"`
}

// ==========================================
// 2. Resolver Interface
// ==========================================

// WrapperDemoResolver 定义模块业务逻辑接口
type WrapperDemoResolver[T any] interface {

	// GetArticle GET /articles/:id
	GetArticle(ctx context.Context, id *int) (*Article, error)

	// ListArticles GET /articles/list
	ListArticles(ctx context.Context, input *ListArticlesArgs) (*[]*Article, error)

	// ListArticlesV2 GET /articles/list/v2
	ListArticlesV2(ctx context.Context, input *ListArticlesV2Args) (*ListResArticle, error)

	// CreateArticle POST /articles/create
	CreateArticle(ctx context.Context, input *CreateArticleArgs) (*Article, error)

	// GetArticleRaw GET /articles/raw/:id
	GetArticleRaw(ctx context.Context, id *int) (*Article, error)

	// Logout POST /articles/logout
	Logout(ctx context.Context) error
}

// ==========================================
// 3. Executor / Binders
// ==========================================

/*
Resgen 自动化执行流说明:
1. Request Decorators  : 全局与特化请求拦截 (Auth, RateLimit 等)
2. Binding & Validation: 自动参数绑定与核心规则校验
3. Invoke Decorators   : 业务调用前的特化处理 (OwnerCheck 等)
4. Business Logic      : 调用 Resolver 接口实现的业务逻辑
5. Response Decorators : 结果脱敏或格式转换 (MaskEmail 等)
6. Result Response     : 最终结果渲染响应
*/

func MountWrapperDemo[T any, C ServerContext[T]](en *Engine[C], biz WrapperDemoResolver[T]) {
	d, _ := en.Decorator().(Decorator[T])
	v, _ := en.Validator().(Validator[T])
	r, _ := en.Responder().(Responder[T])
	executor := &WrapperDemoExecutor[T, C]{
		en:  en,
		biz: biz,
		d:   d,
		v:   v,
		r:   r,
	}

	executor.mount()
}

type WrapperDemoExecutor[T any, C ServerContext[T]] struct {
	en  *Engine[C]
	biz WrapperDemoResolver[T]
	d   Decorator[T]
	v   Validator[T]
	r   Responder[T]
}

func (e *WrapperDemoExecutor[T, C]) mount() {

	// --- 注册组: Articles ---

	infoGetArticle := MethodInfo{
		Module: "WrapperDemo",
		Group:  "/articles",
		Method: "GET",
		Name:   "GetArticle",
		Path:   "/articles/:id",
	}
	e.register(infoGetArticle, e.handleGetArticle)

	infoListArticles := MethodInfo{
		Module: "WrapperDemo",
		Group:  "/articles",
		Method: "GET",
		Name:   "ListArticles",
		Path:   "/articles/list",
	}
	e.register(infoListArticles, e.handleListArticles)

	infoListArticlesV2 := MethodInfo{
		Module: "WrapperDemo",
		Group:  "/articles",
		Method: "GET",
		Name:   "ListArticlesV2",
		Path:   "/articles/list/v2",
	}
	e.register(infoListArticlesV2, e.handleListArticlesV2)

	infoCreateArticle := MethodInfo{
		Module: "WrapperDemo",
		Group:  "/articles",
		Method: "POST",
		Name:   "CreateArticle",
		Path:   "/articles/create",
	}
	e.register(infoCreateArticle, e.handleCreateArticle)

	infoGetArticleRaw := MethodInfo{
		Module: "WrapperDemo",
		Group:  "/articles",
		Method: "GET",
		Name:   "GetArticleRaw",
		Path:   "/articles/raw/:id",
	}
	e.register(infoGetArticleRaw, e.handleGetArticleRaw)

	infoLogout := MethodInfo{
		Module: "WrapperDemo",
		Group:  "/articles",
		Method: "POST",
		Name:   "Logout",
		Path:   "/articles/logout",
	}
	e.register(infoLogout, e.handleLogout)
}

func (e *WrapperDemoExecutor[T, C]) register(info MethodInfo, handler HandlerFunc[C]) {
	info.HandlerPos = GetHandlerJumpPath(e.biz, info.Name)
	e.en.Register(info, handler)
}

// handleGetArticle 封装了端点的自动化执行流
func (e *WrapperDemoExecutor[T, C]) handleGetArticle(request C, info MethodInfo) {
	native := request.Native()
	var idVal *int

	if val := request.GetPath("id"); val != "" {
		if v, err := IntFromParam(val); err == nil {
			v2 := v
			idVal = &v2
		} else {
			request.RenderJson(e.r.ErrorToStatus(native, err), e.r.BindResData(native, nil, err))
			return
		}
	}
	result, err := e.biz.GetArticle(request.Context(), idVal)
	if err != nil {
		request.RenderJson(e.r.ErrorToStatus(native, err), e.r.BindResData(native, nil, err))
		return
	}
	request.RenderJson(200, e.r.BindResData(native, result, nil))
}

// handleListArticles 封装了端点的自动化执行流
func (e *WrapperDemoExecutor[T, C]) handleListArticles(request C, info MethodInfo) {
	native := request.Native()
	var input ListArticlesArgs
	if err := e.bindListArticles(request, &input); err != nil {
		request.RenderJson(e.r.ErrorToStatus(native, err), e.r.BindResData(native, nil, err))
		return
	}
	result, err := e.biz.ListArticles(request.Context(), &input)
	if err != nil {
		request.RenderJson(e.r.ErrorToStatus(native, err), e.r.BindResData(native, nil, err))
		return
	}
	request.RenderJson(200, e.r.BindResData(native, result, nil))
}

// bindListArticles 自动生成的参数提取与转换实现
func (e *WrapperDemoExecutor[T, C]) bindListArticles(request C, input *ListArticlesArgs) error {
	if val := request.GetQuery("page"); val != "" {
		if v, err := IntFromParam(val); err == nil {
			v2 := v
			input.Page = &v2
		} else {
			return err
		}
	}
	if val := request.GetQuery("size"); val != "" {
		if v, err := IntFromParam(val); err == nil {
			v2 := v
			input.Size = &v2
		} else {
			return err
		}
	}
	return nil
}

// handleListArticlesV2 封装了端点的自动化执行流
func (e *WrapperDemoExecutor[T, C]) handleListArticlesV2(request C, info MethodInfo) {
	native := request.Native()
	var input ListArticlesV2Args
	if err := e.bindListArticlesV2(request, &input); err != nil {
		request.RenderJson(e.r.ErrorToStatus(native, err), e.r.BindResData(native, nil, err))
		return
	}
	result, err := e.biz.ListArticlesV2(request.Context(), &input)
	if err != nil {
		request.RenderJson(e.r.ErrorToStatus(native, err), e.r.BindResData(native, nil, err))
		return
	}
	request.RenderJson(200, e.r.BindResData(native, result, nil))
}

// bindListArticlesV2 自动生成的参数提取与转换实现
func (e *WrapperDemoExecutor[T, C]) bindListArticlesV2(request C, input *ListArticlesV2Args) error {
	if val := request.GetQuery("page"); val != "" {
		if v, err := IntFromParam(val); err == nil {
			v2 := v
			input.Page = &v2
		} else {
			return err
		}
	}
	if val := request.GetQuery("size"); val != "" {
		if v, err := IntFromParam(val); err == nil {
			v2 := v
			input.Size = &v2
		} else {
			return err
		}
	}
	return nil
}

// handleCreateArticle 封装了端点的自动化执行流
func (e *WrapperDemoExecutor[T, C]) handleCreateArticle(request C, info MethodInfo) {
	native := request.Native()
	var input CreateArticleArgs
	if err := e.bindCreateArticle(request, &input); err != nil {
		request.RenderJson(e.r.ErrorToStatus(native, err), e.r.BindResData(native, nil, err))
		return
	}
	if err := e.validateCreateArticle(native, &input); err != nil {
		request.RenderJson(e.r.ErrorToStatus(native, err), e.r.BindResData(native, nil, err))
		return
	}
	result, err := e.biz.CreateArticle(request.Context(), &input)
	if err != nil {
		request.RenderJson(e.r.ErrorToStatus(native, err), e.r.BindResData(native, nil, err))
		return
	}
	request.RenderJson(201, e.r.BindResData(native, result, nil))
}

// bindCreateArticle 自动生成的参数提取与转换实现
func (e *WrapperDemoExecutor[T, C]) bindCreateArticle(request C, input *CreateArticleArgs) error {
	if err := request.Payload(SourceJson, input); err != nil {
		return err
	}
	return nil
}

// validateCreateArticle 参数验证逻辑
func (e *WrapperDemoExecutor[T, C]) validateCreateArticle(ctx T, input *CreateArticleArgs) error {
	// Pass 1: Required validations for top-level arguments and their fields
	if err := e.v.Required(ctx, "title", input.Title); err != nil {
		return err
	}
	if err := e.v.Required(ctx, "content", input.Content); err != nil {
		return err
	}

	// Pass 2: Other validations
	return nil
}

// handleGetArticleRaw 封装了端点的自动化执行流
func (e *WrapperDemoExecutor[T, C]) handleGetArticleRaw(request C, info MethodInfo) {
	native := request.Native()
	var idVal *int

	if val := request.GetPath("id"); val != "" {
		if v, err := IntFromParam(val); err == nil {
			v2 := v
			idVal = &v2
		} else {
			request.RenderJson(e.r.ErrorToStatus(native, err), err.Error())
			return
		}
	}
	result, err := e.biz.GetArticleRaw(request.Context(), idVal)
	if err != nil {
		request.RenderJson(e.r.ErrorToStatus(native, err), err.Error())
		return
	}
	request.RenderJson(200, result)
}

// handleLogout 封装了端点的自动化执行流
func (e *WrapperDemoExecutor[T, C]) handleLogout(request C, info MethodInfo) {
	native := request.Native()
	err := e.biz.Logout(request.Context())
	if err != nil {
		request.RenderJson(e.r.ErrorToStatus(native, err), e.r.BindResData(native, nil, err))
		return
	}
	request.RenderJson(200, nil)
}
