// Code generated by github.com/xslasd/resgen v0.5.0. DO NOT EDIT.
// This file will be automatically regenerated based on the schema.

package resolver

import (
	"context"
)

// ==========================================
// 1. Models
// ==========================================

// Item 输出模型
type Item struct {
	Id   int    `json:"id"`
	Name string `json:"name"`
}

// ==========================================
// 2. Resolver Interface
// ==========================================

// SinglePayloadExampleResolver 定义模块业务逻辑接口
type SinglePayloadExampleResolver[T any] interface {

	// SaveItems POST /api/items
	SaveItems(ctx context.Context, input *[]Item) (int, error)

	// ProcessRaw POST /api/raw
	ProcessRaw(ctx context.Context, input *any) (any, error)
}

// ==========================================
// 3. Executor / Binders
// ==========================================

/*
Resgen 自动化执行流说明:
1. Request Decorators  : 全局与特化请求拦截 (Auth, RateLimit 等)
2. Binding & Validation: 自动参数绑定与核心规则校验
3. Invoke Decorators   : 业务调用前的特化处理 (OwnerCheck 等)
4. Business Logic      : 调用 Resolver 接口实现的业务逻辑
5. Response Decorators : 结果脱敏或格式转换 (MaskEmail 等)
6. Result Response     : 最终结果渲染响应
*/

func MountSinglePayloadExample[T any, C ServerContext[T]](en *Engine[C], biz SinglePayloadExampleResolver[T]) {
	d, _ := en.Decorator().(Decorator[T])
	v, _ := en.Validator().(Validator[T])
	r, _ := en.Responder().(Responder[T])
	executor := &SinglePayloadExampleExecutor[T, C]{
		en:  en,
		biz: biz,
		d:   d,
		v:   v,
		r:   r,
	}

	executor.mount()
}

type SinglePayloadExampleExecutor[T any, C ServerContext[T]] struct {
	en  *Engine[C]
	biz SinglePayloadExampleResolver[T]
	d   Decorator[T]
	v   Validator[T]
	r   Responder[T]
}

func (e *SinglePayloadExampleExecutor[T, C]) mount() {

	// --- 注册组: Api ---

	infoSaveItems := MethodInfo{
		Module: "SinglePayloadExample",
		Group:  "/api",
		Method: "POST",
		Name:   "SaveItems",
		Path:   "/api/items",
	}
	e.register(infoSaveItems, e.handleSaveItems)

	infoProcessRaw := MethodInfo{
		Module: "SinglePayloadExample",
		Group:  "/api",
		Method: "POST",
		Name:   "ProcessRaw",
		Path:   "/api/raw",
	}
	e.register(infoProcessRaw, e.handleProcessRaw)
}

func (e *SinglePayloadExampleExecutor[T, C]) register(info MethodInfo, handler HandlerFunc[C]) {
	info.HandlerPos = GetHandlerJumpPath(e.biz, info.Name)
	e.en.Register(info, handler)
}

// handleSaveItems 封装了端点的自动化执行流
func (e *SinglePayloadExampleExecutor[T, C]) handleSaveItems(request C, info MethodInfo) {
	native := request.Native()
	var input []Item
	if err := e.bindSaveItems(request, &input); err != nil {
		request.RenderJson(e.r.ErrorToStatus(native, err), e.r.BindRes(native, nil, err))
		return
	}
	if err := e.validateSaveItems(native, &input); err != nil {
		request.RenderJson(e.r.ErrorToStatus(native, err), e.r.BindRes(native, nil, err))
		return
	}
	result, err := e.biz.SaveItems(request.Context(), &input)
	if err != nil {
		request.RenderJson(e.r.ErrorToStatus(native, err), e.r.BindRes(native, nil, err))
		return
	}
	request.RenderJson(200, e.r.BindRes(native, result, nil))
}

// bindSaveItems 自动生成的参数提取与转换实现
func (e *SinglePayloadExampleExecutor[T, C]) bindSaveItems(request C, input *[]Item) error {
	if err := request.Payload(SourceJson, input); err != nil {
		return err
	}
	return nil
}

// validateSaveItems 参数验证逻辑
func (e *SinglePayloadExampleExecutor[T, C]) validateSaveItems(ctx T, input *[]Item) error {
	return nil
}

// handleProcessRaw 封装了端点的自动化执行流
func (e *SinglePayloadExampleExecutor[T, C]) handleProcessRaw(request C, info MethodInfo) {
	native := request.Native()
	var input any
	if err := e.bindProcessRaw(request, &input); err != nil {
		request.RenderJson(e.r.ErrorToStatus(native, err), e.r.BindRes(native, nil, err))
		return
	}
	result, err := e.biz.ProcessRaw(request.Context(), &input)
	if err != nil {
		request.RenderJson(e.r.ErrorToStatus(native, err), e.r.BindRes(native, nil, err))
		return
	}
	request.RenderJson(200, e.r.BindRes(native, result, nil))
}

// bindProcessRaw 自动生成的参数提取与转换实现
func (e *SinglePayloadExampleExecutor[T, C]) bindProcessRaw(request C, input *any) error {
	if err := request.Payload(SourceJson, input); err != nil {
		return err
	}
	return nil
}
