// Code generated by github.com/xslasd/resgen v0.1.0. DO NOT EDIT.
// This file will be automatically regenerated based on the schema.

package resolver

import (
	"context"
)

// ==========================================
// 1. Models
// ==========================================

// User 输出模型
type User struct {
	Id       int    `json:"id"`
	Username string `json:"username"`
	Email    string `json:"email"`
}

// Token 输出模型
type Token struct {
	Token     string `json:"token"`
	ExpiresAt int    `json:"expires_at"`
}

// RegisterInput 输入模型
type RegisterInput struct {
	Username string `json:"username"`
	Email    string `json:"email"`
	Mobile   string `json:"mobile"`
	Password string `json:"password"`
}

// UpdateInput 输入模型
type UpdateInput struct {
	Id    int     `json:"id"`
	Email *string `json:"email"`
}

// LoginArgs 输入模型
type LoginArgs struct {
	Username *string `json:"username"`
	Password *string `json:"password"`
}

// ==========================================
// 2. Resolver Interface
// ==========================================

// AuthDemoResolver 定义模块业务逻辑接口
type AuthDemoResolver[T any] interface {

	// Register POST /auth/register
	Register(ctx context.Context, input *RegisterInput) (*User, error)

	BindLogin(request ServerContextBase, input *LoginArgs) error
	ValidateLogin(ctx T, input *LoginArgs) error
	// Login POST /auth/login
	Login(ctx context.Context, input *LoginArgs) (*Token, error)

	// GetMe GET /auth/me
	GetMe(ctx context.Context) (*User, error)

	OnInvoke_CheckOwner_UpdateUser(ctx T, info MethodInfo, input *UpdateInput) error
	// UpdateUser POST /auth/update
	UpdateUser(ctx context.Context, input *UpdateInput) (*User, error)
	OnResponse_MaskEmail_UpdateUser(ctx T, info MethodInfo, input *UpdateInput, result *User, err error) (*User, error)

	// DeleteUser DELETE /auth/:id
	DeleteUser(ctx context.Context, id *int) (*string, error)
}

// ==========================================
// 3. Executor / Binders
// ==========================================

/*
Resgen 自动化执行流说明:
1. Request Decorators  : 全局与特化请求拦截 (Auth, RateLimit 等)
2. Binding & Validation: 自动参数绑定与核心规则校验
3. Invoke Decorators   : 业务调用前的特化处理 (OwnerCheck 等)
4. Business Logic      : 调用 Resolver 接口实现的业务逻辑
5. Response Decorators : 结果脱敏或格式转换 (MaskEmail 等)
6. Result Response     : 最终结果渲染响应
*/

func MountAuthDemo[T any, C ServerContext[T]](en *Engine[C], biz AuthDemoResolver[T]) {
	d, _ := en.Decorator().(Decorator[T])
	v, _ := en.Validator().(Validator[T])
	r, _ := en.Responder().(Responder[T])
	executor := &AuthDemoExecutor[T, C]{
		en:  en,
		biz: biz,
		d:   d,
		v:   v,
		r:   r,
	}

	executor.mount()
}

type AuthDemoExecutor[T any, C ServerContext[T]] struct {
	en  *Engine[C]
	biz AuthDemoResolver[T]
	d   Decorator[T]
	v   Validator[T]
	r   Responder[T]
}

func (e *AuthDemoExecutor[T, C]) mount() {

	// --- 注册组: Auth ---

	infoRegister := MethodInfo{
		Module: "AuthDemo",
		Group:  "/auth",
		Method: "POST",
		Name:   "Register",
		Path:   "/auth/register",
	}
	e.en.Register(infoRegister, e.handleRegister)

	infoLogin := MethodInfo{
		Module: "AuthDemo",
		Group:  "/auth",
		Method: "POST",
		Name:   "Login",
		Path:   "/auth/login",
	}
	e.en.Register(infoLogin, e.handleLogin)

	infoGetMe := MethodInfo{
		Module: "AuthDemo",
		Group:  "/auth",
		Method: "GET",
		Name:   "GetMe",
		Path:   "/auth/me",
	}
	e.en.Register(infoGetMe, e.handleGetMe)

	infoUpdateUser := MethodInfo{
		Module: "AuthDemo",
		Group:  "/auth",
		Method: "POST",
		Name:   "UpdateUser",
		Path:   "/auth/update",
	}
	e.en.Register(infoUpdateUser, e.handleUpdateUser)

	infoDeleteUser := MethodInfo{
		Module: "AuthDemo",
		Group:  "/auth",
		Method: "DELETE",
		Name:   "DeleteUser",
		Path:   "/auth/:id",
	}
	e.en.Register(infoDeleteUser, e.handleDeleteUser)
}

// handleRegister 封装了端点的自动化执行流
func (e *AuthDemoExecutor[T, C]) handleRegister(request C, info MethodInfo) {
	native := request.Native()
	var input RegisterInput
	if err := e.bindRegister(request, &input); err != nil {
		request.RenderJson(e.r.ErrorToStatus(native, err), e.r.BindResData(native, nil, err))
		return
	}
	if err := e.validateRegister(native, &input); err != nil {
		request.RenderJson(e.r.ErrorToStatus(native, err), e.r.BindResData(native, nil, err))
		return
	}
	result, err := e.biz.Register(request.Context(), &input)
	if err != nil {
		request.RenderJson(e.r.ErrorToStatus(native, err), e.r.BindResData(native, nil, err))
		return
	}
	request.RenderJson(201, e.r.BindResData(native, result, nil))
}

// bindRegister 自动生成的参数提取与转换实现
func (e *AuthDemoExecutor[T, C]) bindRegister(request C, input *RegisterInput) error {
	if err := request.Payload(SourceForm, input); err != nil {
		return err
	}
	return nil
}

// validateRegister 参数验证逻辑
func (e *AuthDemoExecutor[T, C]) validateRegister(ctx T, input *RegisterInput) error {
	// Pass 1: Required validations
	if err := e.v.Required(ctx, "username", input.Username); err != nil {
		return err
	}
	if err := e.v.Required(ctx, "email", input.Email); err != nil {
		return err
	}
	if err := e.v.Required(ctx, "mobile", input.Mobile); err != nil {
		return err
	}
	if err := e.v.Required(ctx, "password", input.Password); err != nil {
		return err
	}

	// Pass 2: Other validations
	if err := e.v.Min(ctx, "username", input.Username, 3); err != nil {
		return err
	}
	if err := e.v.Max(ctx, "username", input.Username, 20); err != nil {
		return err
	}
	if err := e.v.Email(ctx, "email", input.Email); err != nil {
		return err
	}
	if err := e.v.Mobile(ctx, "mobile", input.Mobile); err != nil {
		return err
	}
	if err := e.v.Min(ctx, "password", input.Password, 8); err != nil {
		return err
	}
	return nil
}

// handleLogin 封装了端点的自动化执行流
func (e *AuthDemoExecutor[T, C]) handleLogin(request C, info MethodInfo) {
	native := request.Native()
	var input LoginArgs
	if err := e.biz.BindLogin(request, &input); err != nil {
		request.RenderJson(e.r.ErrorToStatus(native, err), e.r.BindResData(native, nil, err))
		return
	}
	if err := e.biz.ValidateLogin(native, &input); err != nil {
		request.RenderJson(e.r.ErrorToStatus(native, err), e.r.BindResData(native, nil, err))
		return
	}
	result, err := e.biz.Login(request.Context(), &input)
	if err != nil {
		request.RenderJson(e.r.ErrorToStatus(native, err), e.r.BindResData(native, nil, err))
		return
	}
	request.RenderJson(200, e.r.BindResData(native, result, nil))
}

// handleGetMe 封装了端点的自动化执行流
func (e *AuthDemoExecutor[T, C]) handleGetMe(request C, info MethodInfo) {
	native := request.Native()
	if err := e.d.LoginRequired(native, info); err != nil {
		request.RenderJson(e.r.ErrorToStatus(native, err), e.r.BindResData(native, nil, err))
		return
	}
	result, err := e.biz.GetMe(request.Context())
	if err != nil {
		request.RenderJson(e.r.ErrorToStatus(native, err), e.r.BindResData(native, nil, err))
		return
	}
	request.RenderJson(200, e.r.BindResData(native, result, nil))
}

// handleUpdateUser 封装了端点的自动化执行流
func (e *AuthDemoExecutor[T, C]) handleUpdateUser(request C, info MethodInfo) {
	native := request.Native()
	if err := e.d.LoginRequired(native, info); err != nil {
		request.RenderJson(e.r.ErrorToStatus(native, err), e.r.BindResData(native, nil, err))
		return
	}
	var input UpdateInput
	if err := e.bindUpdateUser(request, &input); err != nil {
		request.RenderJson(e.r.ErrorToStatus(native, err), e.r.BindResData(native, nil, err))
		return
	}
	if err := e.validateUpdateUser(native, &input); err != nil {
		request.RenderJson(e.r.ErrorToStatus(native, err), e.r.BindResData(native, nil, err))
		return
	}
	if err := e.biz.OnInvoke_CheckOwner_UpdateUser(native, info, &input); err != nil {
		request.RenderJson(e.r.ErrorToStatus(native, err), e.r.BindResData(native, nil, err))
		return
	}
	result, err := e.biz.UpdateUser(request.Context(), &input)
	if res, rerr := e.biz.OnResponse_MaskEmail_UpdateUser(native, info, &input, result, err); rerr != nil {
		request.RenderJson(e.r.ErrorToStatus(native, rerr), e.r.BindResData(native, nil, rerr))
		return
	} else {
		result = res
		err = rerr
	}
	if err != nil {
		request.RenderJson(e.r.ErrorToStatus(native, err), e.r.BindResData(native, nil, err))
		return
	}
	request.RenderJson(200, e.r.BindResData(native, result, nil))
}

// bindUpdateUser 自动生成的参数提取与转换实现
func (e *AuthDemoExecutor[T, C]) bindUpdateUser(request C, input *UpdateInput) error {
	if err := request.Payload(SourceJson, input); err != nil {
		return err
	}
	return nil
}

// validateUpdateUser 参数验证逻辑
func (e *AuthDemoExecutor[T, C]) validateUpdateUser(ctx T, input *UpdateInput) error {
	// Pass 1: Required validations
	if err := e.v.Required(ctx, "id", input.Id); err != nil {
		return err
	}

	// Pass 2: Other validations
	if input.Email != nil {
		if err := e.v.Email(ctx, "email", *input.Email); err != nil {
			return err
		}
	}
	return nil
}

// handleDeleteUser 封装了端点的自动化执行流
func (e *AuthDemoExecutor[T, C]) handleDeleteUser(request C, info MethodInfo) {
	native := request.Native()
	if err := e.d.Auth(native, info, "admin"); err != nil {
		request.RenderJson(e.r.ErrorToStatus(native, err), e.r.BindResData(native, nil, err))
		return
	}
	if err := e.d.LoginRequired(native, info); err != nil {
		request.RenderJson(e.r.ErrorToStatus(native, err), e.r.BindResData(native, nil, err))
		return
	}
	var idVal *int

	if val := request.GetPath("id"); val != "" {
		if v, err := IntFromParam(val); err == nil {
			v2 := v
			idVal = &v2
		} else {
			request.RenderJson(e.r.ErrorToStatus(native, err), e.r.BindResData(native, nil, err))
			return
		}
	}
	result, err := e.biz.DeleteUser(request.Context(), idVal)
	if err != nil {
		request.RenderJson(e.r.ErrorToStatus(native, err), e.r.BindResData(native, nil, err))
		return
	}
	request.RenderJson(200, e.r.BindResData(native, result, nil))
}
