// Code generated by github.com/xslasd/resgen v0.3.3. DO NOT EDIT.
// This file will be automatically regenerated based on the schema.

package resolver

import (
	"context"
	"mime/multipart"
)

// ==========================================
// 1. Models
// ==========================================

// UploadAvatarInput 输入模型
type UploadAvatarInput struct {
	UserId int                   `json:"user_id"`
	Avatar *multipart.FileHeader `json:"avatar"`
}

// UploadDocumentInput 输入模型
type UploadDocumentInput struct {
	Title       string                `json:"title"`
	Description *string               `json:"description"`
	Document    *multipart.FileHeader `json:"document"`
	Cover       *multipart.FileHeader `json:"cover"`
}

// UploadResult 输出模型
type UploadResult struct {
	FileUrl  string `json:"file_url"`
	FileSize int    `json:"file_size"`
	MimeType string `json:"mime_type"`
}

// ListResArticle 输出模型
type ListResArticle struct {
	Rows  []Article `json:"rows"`
	Total int       `json:"total"`
}

// ==========================================
// 2. Resolver Interface
// ==========================================

// FileDemoResolver 定义模块业务逻辑接口
type FileDemoResolver[T any] interface {

	// UploadAvatar POST /files/avatar
	UploadAvatar(ctx context.Context, input *UploadAvatarInput) (*UploadResult, error)

	// UploadDocument POST /files/document
	UploadDocument(ctx context.Context, input *UploadDocumentInput) (*UploadResult, error)

	// DownloadFile GET /files/download/:id
	DownloadFile(ctx context.Context, id *int) (*string, error)

	// ExportCsv GET /files/export/csv
	ExportCsv(ctx context.Context, ids *string) (*string, error)
}

// ==========================================
// 3. Executor / Binders
// ==========================================

/*
Resgen 自动化执行流说明:
1. Request Decorators  : 全局与特化请求拦截 (Auth, RateLimit 等)
2. Binding & Validation: 自动参数绑定与核心规则校验
3. Invoke Decorators   : 业务调用前的特化处理 (OwnerCheck 等)
4. Business Logic      : 调用 Resolver 接口实现的业务逻辑
5. Response Decorators : 结果脱敏或格式转换 (MaskEmail 等)
6. Result Response     : 最终结果渲染响应
*/

func MountFileDemo[T any, C ServerContext[T]](en *Engine[C], biz FileDemoResolver[T]) {
	d, _ := en.Decorator().(Decorator[T])
	v, _ := en.Validator().(Validator[T])
	r, _ := en.Responder().(Responder[T])
	executor := &FileDemoExecutor[T, C]{
		en:  en,
		biz: biz,
		d:   d,
		v:   v,
		r:   r,
	}

	executor.mount()
}

type FileDemoExecutor[T any, C ServerContext[T]] struct {
	en  *Engine[C]
	biz FileDemoResolver[T]
	d   Decorator[T]
	v   Validator[T]
	r   Responder[T]
}

func (e *FileDemoExecutor[T, C]) mount() {

	// --- 注册组: Files ---

	infoUploadAvatar := MethodInfo{
		Module: "FileDemo",
		Group:  "/files",
		Method: "POST",
		Name:   "UploadAvatar",
		Path:   "/files/avatar",
	}
	e.register(infoUploadAvatar, e.handleUploadAvatar)

	infoUploadDocument := MethodInfo{
		Module: "FileDemo",
		Group:  "/files",
		Method: "POST",
		Name:   "UploadDocument",
		Path:   "/files/document",
	}
	e.register(infoUploadDocument, e.handleUploadDocument)

	infoDownloadFile := MethodInfo{
		Module: "FileDemo",
		Group:  "/files",
		Method: "GET",
		Name:   "DownloadFile",
		Path:   "/files/download/:id",
	}
	e.register(infoDownloadFile, e.handleDownloadFile)

	infoExportCsv := MethodInfo{
		Module: "FileDemo",
		Group:  "/files",
		Method: "GET",
		Name:   "ExportCsv",
		Path:   "/files/export/csv",
	}
	e.register(infoExportCsv, e.handleExportCsv)
}

func (e *FileDemoExecutor[T, C]) register(info MethodInfo, handler HandlerFunc[C]) {
	info.HandlerPos = GetHandlerJumpPath(e.biz, info.Name)
	e.en.Register(info, handler)
}

// handleUploadAvatar 封装了端点的自动化执行流
func (e *FileDemoExecutor[T, C]) handleUploadAvatar(request C, info MethodInfo) {
	native := request.Native()
	var input UploadAvatarInput
	if err := e.bindUploadAvatar(request, &input); err != nil {
		request.RenderJson(e.r.ErrorToStatus(native, err), e.r.BindResData(native, nil, err))
		return
	}
	if err := e.validateUploadAvatar(native, &input); err != nil {
		request.RenderJson(e.r.ErrorToStatus(native, err), e.r.BindResData(native, nil, err))
		return
	}
	result, err := e.biz.UploadAvatar(request.Context(), &input)
	if err != nil {
		request.RenderJson(e.r.ErrorToStatus(native, err), e.r.BindResData(native, nil, err))
		return
	}
	request.RenderJson(201, e.r.BindResData(native, result, nil))
}

// bindUploadAvatar 自动生成的参数提取与转换实现
func (e *FileDemoExecutor[T, C]) bindUploadAvatar(request C, input *UploadAvatarInput) error {
	if err := request.Payload(SourceMultipart, input); err != nil {
		return err
	}
	return nil
}

// validateUploadAvatar 参数验证逻辑
func (e *FileDemoExecutor[T, C]) validateUploadAvatar(ctx T, input *UploadAvatarInput) error {
	// Pass 1: Required validations
	if err := e.v.Required(ctx, "userId", input.UserId); err != nil {
		return err
	}
	if err := e.v.Required(ctx, "avatar", input.Avatar); err != nil {
		return err
	}

	// Pass 2: Other validations
	if input.Avatar != nil {
		if err := e.v.FileRule(ctx, "avatar", *input.Avatar, 2097152, []string{"image/jpeg", "image/png"}, "头像仅支持 JPG/PNG 格式，且不超过 2MB"); err != nil {
			return err
		}
	}
	return nil
}

// handleUploadDocument 封装了端点的自动化执行流
func (e *FileDemoExecutor[T, C]) handleUploadDocument(request C, info MethodInfo) {
	native := request.Native()
	var input UploadDocumentInput
	if err := e.bindUploadDocument(request, &input); err != nil {
		request.RenderJson(e.r.ErrorToStatus(native, err), e.r.BindResData(native, nil, err))
		return
	}
	if err := e.validateUploadDocument(native, &input); err != nil {
		request.RenderJson(e.r.ErrorToStatus(native, err), e.r.BindResData(native, nil, err))
		return
	}
	result, err := e.biz.UploadDocument(request.Context(), &input)
	if err != nil {
		request.RenderJson(e.r.ErrorToStatus(native, err), e.r.BindResData(native, nil, err))
		return
	}
	request.RenderJson(201, e.r.BindResData(native, result, nil))
}

// bindUploadDocument 自动生成的参数提取与转换实现
func (e *FileDemoExecutor[T, C]) bindUploadDocument(request C, input *UploadDocumentInput) error {
	if err := request.Payload(SourceMultipart, input); err != nil {
		return err
	}
	return nil
}

// validateUploadDocument 参数验证逻辑
func (e *FileDemoExecutor[T, C]) validateUploadDocument(ctx T, input *UploadDocumentInput) error {
	// Pass 1: Required validations
	if err := e.v.Required(ctx, "title", input.Title); err != nil {
		return err
	}
	if err := e.v.Required(ctx, "document", input.Document); err != nil {
		return err
	}

	// Pass 2: Other validations
	if input.Document != nil {
		if err := e.v.FileRule(ctx, "document", *input.Document, 10485760, []string{"application/pdf"}, "仅支持 PDF 格式，且不超过 10MB"); err != nil {
			return err
		}
	}
	if input.Cover != nil {
		if err := e.v.FileRule(ctx, "cover", *input.Cover, 1048576, []string{"image/jpeg", "image/png", "image/webp"}, "封面图仅支持 JPG/PNG/WebP 格式，且不超过 1MB"); err != nil {
			return err
		}
	}
	return nil
}

// handleDownloadFile 封装了端点的自动化执行流
func (e *FileDemoExecutor[T, C]) handleDownloadFile(request C, info MethodInfo) {
	native := request.Native()
	var idVal *int

	if val := request.GetPath("id"); val != "" {
		if v, err := IntFromParam(val); err == nil {
			v2 := v
			idVal = &v2
		} else {
			request.RenderJson(e.r.ErrorToStatus(native, err), e.r.BindResData(native, nil, err))
			return
		}
	}
	result, err := e.biz.DownloadFile(request.Context(), idVal)
	if err != nil {
		request.RenderJson(e.r.ErrorToStatus(native, err), e.r.BindResData(native, nil, err))
		return
	}
	request.RenderText(200, result)
}

// handleExportCsv 封装了端点的自动化执行流
func (e *FileDemoExecutor[T, C]) handleExportCsv(request C, info MethodInfo) {
	native := request.Native()
	var idsVal *string

	if val := request.GetQuery("ids"); val != "" {
		idsVal = &val
	}
	result, err := e.biz.ExportCsv(request.Context(), idsVal)
	if err != nil {
		request.RenderJson(e.r.ErrorToStatus(native, err), e.r.BindResData(native, nil, err))
		return
	}
	request.RenderText(200, result)
}
