// Code generated by github.com/xslasd/resgen. DO NOT EDIT.
// This file will be automatically regenerated based on the schema.

package resolver

import (
	"context"
	"time"

	"github.com/xslasd/resgen/examples/scalars"
)

// ==========================================
// 1. Models
// ==========================================

// Event 输出模型
type Event struct {
	Id        int        `json:"id"`
	Name      string     `json:"name"`
	StartTime time.Time  `json:"start_time"`
	EndTime   *time.Time `json:"end_time"`
	CreatedAt *time.Time `json:"created_at"`
}

// EventDTO 数据传输对象
type EventDTO struct {
	Id        int    `json:"id"`
	Name      string `json:"name"`
	StartTime Int    `json:"start_time"`
	EndTime   *Int   `json:"end_time"`
	CreatedAt *Int   `json:"created_at"`
}

func (m *Event) ToDTO(ctx any) (*EventDTO, error) {
	if m == nil {
		return nil, nil
	}
	dto := &EventDTO{}
	dto.Id = m.Id
	dto.Name = m.Name
	tmpStartTime := scalars.IntTime(m.StartTime)
	valStartTime, err := tmpStartTime.ToValue(ctx)
	if err != nil {
		return nil, err
	}
	dto.StartTime = valStartTime
	if m.EndTime != nil {
		tmpEndTime := scalars.IntTime(*m.EndTime)
		valEndTime, err := tmpEndTime.ToValue(ctx)
		if err != nil {
			return nil, err
		}
		dto.EndTime = &valEndTime
	}
	if m.CreatedAt != nil {
		tmpCreatedAt := scalars.IntTime(*m.CreatedAt)
		valCreatedAt, err := tmpCreatedAt.ToValue(ctx)
		if err != nil {
			return nil, err
		}
		dto.CreatedAt = &valCreatedAt
	}
	return dto, nil
}

func (m *Event) FromDTO(ctx any, dto *EventDTO) error {
	if m == nil || dto == nil {
		return nil
	}
	m.Id = dto.Id
	m.Name = dto.Name
	var tmpStartTime scalars.IntTime
	if err := tmpStartTime.FromValue(ctx, dto.StartTime); err != nil {
		return err
	}
	m.StartTime = time.Time(tmpStartTime)
	if dto.EndTime != nil {
		var tmp scalars.IntTime
		if err := tmp.FromValue(ctx, *dto.EndTime); err != nil {
			return err
		}
		targetVal := time.Time(tmp)
		m.EndTime = &targetVal
	}
	if dto.CreatedAt != nil {
		var tmp scalars.IntTime
		if err := tmp.FromValue(ctx, *dto.CreatedAt); err != nil {
			return err
		}
		targetVal := time.Time(tmp)
		m.CreatedAt = &targetVal
	}
	return nil
}

// CreateEventInput 输入模型
type CreateEventInput struct {
	Name      string    `json:"name"`
	StartTime time.Time `json:"start_time"`
	EndTime   time.Time `json:"end_time"`
}

// CreateEventInputDTO 数据传输对象
type CreateEventInputDTO struct {
	Name      string `json:"name"`
	StartTime Int    `json:"start_time"`
	EndTime   Int    `json:"end_time"`
}

func (m *CreateEventInput) ToDTO(ctx any) (*CreateEventInputDTO, error) {
	if m == nil {
		return nil, nil
	}
	dto := &CreateEventInputDTO{}
	dto.Name = m.Name
	tmpStartTime := scalars.IntTime(m.StartTime)
	valStartTime, err := tmpStartTime.ToValue(ctx)
	if err != nil {
		return nil, err
	}
	dto.StartTime = valStartTime
	tmpEndTime := scalars.IntTime(m.EndTime)
	valEndTime, err := tmpEndTime.ToValue(ctx)
	if err != nil {
		return nil, err
	}
	dto.EndTime = valEndTime
	return dto, nil
}

func (m *CreateEventInput) FromDTO(ctx any, dto *CreateEventInputDTO) error {
	if m == nil || dto == nil {
		return nil
	}
	m.Name = dto.Name
	var tmpStartTime scalars.IntTime
	if err := tmpStartTime.FromValue(ctx, dto.StartTime); err != nil {
		return err
	}
	m.StartTime = time.Time(tmpStartTime)
	var tmpEndTime scalars.IntTime
	if err := tmpEndTime.FromValue(ctx, dto.EndTime); err != nil {
		return err
	}
	m.EndTime = time.Time(tmpEndTime)
	return nil
}

// QueryEventsInput 输入模型
type QueryEventsInput struct {
	After  *time.Time `json:"after"`
	Before *time.Time `json:"before"`
	Page   *int       `json:"page"`
	Size   *int       `json:"size"`
}

// QueryEventsInputDTO 数据传输对象
type QueryEventsInputDTO struct {
	After  *Int `json:"after"`
	Before *Int `json:"before"`
	Page   *int `json:"page"`
	Size   *int `json:"size"`
}

func (m *QueryEventsInput) ToDTO(ctx any) (*QueryEventsInputDTO, error) {
	if m == nil {
		return nil, nil
	}
	dto := &QueryEventsInputDTO{}
	if m.After != nil {
		tmpAfter := scalars.IntTime(*m.After)
		valAfter, err := tmpAfter.ToValue(ctx)
		if err != nil {
			return nil, err
		}
		dto.After = &valAfter
	}
	if m.Before != nil {
		tmpBefore := scalars.IntTime(*m.Before)
		valBefore, err := tmpBefore.ToValue(ctx)
		if err != nil {
			return nil, err
		}
		dto.Before = &valBefore
	}
	dto.Page = m.Page
	dto.Size = m.Size
	return dto, nil
}

func (m *QueryEventsInput) FromDTO(ctx any, dto *QueryEventsInputDTO) error {
	if m == nil || dto == nil {
		return nil
	}
	if dto.After != nil {
		var tmp scalars.IntTime
		if err := tmp.FromValue(ctx, *dto.After); err != nil {
			return err
		}
		targetVal := time.Time(tmp)
		m.After = &targetVal
	}
	if dto.Before != nil {
		var tmp scalars.IntTime
		if err := tmp.FromValue(ctx, *dto.Before); err != nil {
			return err
		}
		targetVal := time.Time(tmp)
		m.Before = &targetVal
	}
	m.Page = dto.Page
	m.Size = dto.Size
	return nil
}

// ==========================================
// 2. Resolver Interface
// ==========================================

// ScalarDemoResolver 定义模块业务逻辑接口
type ScalarDemoResolver[T any] interface {

	// GetEventByTime GET /events/:startTime
	GetEventByTime(ctx context.Context, startTime *time.Time) (*Event, error)

	// ListEvents GET /events/list
	ListEvents(ctx context.Context, input *QueryEventsInput) (*[]*Event, error)

	// CreateEvent POST /events/create
	CreateEvent(ctx context.Context, input *CreateEventInput) (*Event, error)
}

// ==========================================
// 3. Executor / Binders
// ==========================================

/*
Resgen 自动化执行流说明:
1. Request Decorators  : 全局与特化请求拦截 (Auth, RateLimit 等)
2. Binding & Validation: 自动参数绑定与核心规则校验
3. Invoke Decorators   : 业务调用前的特化处理 (OwnerCheck 等)
4. Business Logic      : 调用 Resolver 接口实现的业务逻辑
5. Response Decorators : 结果脱敏或格式转换 (MaskEmail 等)
6. Result Response     : 最终结果渲染响应
*/

func MountScalarDemo[T any, C ServerContext[T]](en *Engine[C], biz ScalarDemoResolver[T]) {
	d, _ := en.Decorator().(Decorator[T])
	v, _ := en.Validator().(Validator[T])
	r, _ := en.Responder().(Responder[T])
	executor := &ScalarDemoExecutor[T, C]{
		en:  en,
		biz: biz,
		d:   d,
		v:   v,
		r:   r,
	}

	executor.mount()
}

type ScalarDemoExecutor[T any, C ServerContext[T]] struct {
	en  *Engine[C]
	biz ScalarDemoResolver[T]
	d   Decorator[T]
	v   Validator[T]
	r   Responder[T]
}

func (e *ScalarDemoExecutor[T, C]) mount() {

	// --- 注册组: Events ---

	infoGetEventByTime := MethodInfo{
		Module: "ScalarDemo",
		Group:  "/events",
		Method: "GET",
		Name:   "GetEventByTime",
		Path:   "/events/:startTime",
	}
	e.en.Register(infoGetEventByTime, e.handleGetEventByTime)

	infoListEvents := MethodInfo{
		Module: "ScalarDemo",
		Group:  "/events",
		Method: "GET",
		Name:   "ListEvents",
		Path:   "/events/list",
	}
	e.en.Register(infoListEvents, e.handleListEvents)

	infoCreateEvent := MethodInfo{
		Module: "ScalarDemo",
		Group:  "/events",
		Method: "POST",
		Name:   "CreateEvent",
		Path:   "/events/create",
	}
	e.en.Register(infoCreateEvent, e.handleCreateEvent)
}

// handleGetEventByTime 封装了端点的自动化执行流
func (e *ScalarDemoExecutor[T, C]) handleGetEventByTime(request C, info MethodInfo) {
	native := request.Native()
	var startTimeVal *time.Time

	if val := request.GetPath("startTime"); val != "" {
		var tmp scalars.IntTime
		if err := tmp.FromParam(native, val); err != nil {
			request.RenderJson(e.r.ErrorToStatus(native, err), e.r.BindResData(native, nil, err))
			return
		}
		targetVal := time.Time(tmp)
		startTimeVal = &targetVal
	}
	result, err := e.biz.GetEventByTime(request.Context(), startTimeVal)
	if err != nil {
		request.RenderJson(e.r.ErrorToStatus(native, err), e.r.BindResData(native, nil, err))
		return
	}
	dtoResult, dErr := result.ToDTO(native)
	if dErr != nil {
		request.RenderJson(e.r.ErrorToStatus(native, dErr), e.r.BindResData(native, nil, dErr))
		return
	}
	request.RenderJson(200, e.r.BindResData(native, dtoResult, nil))
}

// handleListEvents 封装了端点的自动化执行流
func (e *ScalarDemoExecutor[T, C]) handleListEvents(request C, info MethodInfo) {
	native := request.Native()
	var input QueryEventsInput
	if err := e.bindListEvents(request, &input); err != nil {
		request.RenderJson(e.r.ErrorToStatus(native, err), e.r.BindResData(native, nil, err))
		return
	}
	result, err := e.biz.ListEvents(request.Context(), &input)
	if err != nil {
		request.RenderJson(e.r.ErrorToStatus(native, err), e.r.BindResData(native, nil, err))
		return
	}
	var dtoResult []*EventDTO
	for _, item := range *result {
		if dto, dErr := item.ToDTO(native); dErr == nil {
			dtoResult = append(dtoResult, dto)
		} else {
			request.RenderJson(e.r.ErrorToStatus(native, dErr), e.r.BindResData(native, nil, dErr))
			return
		}
	}
	request.RenderJson(200, e.r.BindResData(native, dtoResult, nil))
}

// bindListEvents 自动生成的参数提取与转换实现
func (e *ScalarDemoExecutor[T, C]) bindListEvents(request C, input *QueryEventsInput) error {
	if val := request.GetQuery("after"); val != "" {
		var tmp scalars.IntTime
		if err := tmp.FromParam(request.Native(), val); err != nil {
			return err
		}
		targetVal := time.Time(tmp)
		input.After = &targetVal
	}
	if val := request.GetQuery("before"); val != "" {
		var tmp scalars.IntTime
		if err := tmp.FromParam(request.Native(), val); err != nil {
			return err
		}
		targetVal := time.Time(tmp)
		input.Before = &targetVal
	}
	if val := request.GetQuery("page"); val != "" {
		if v, err := IntFromParam(val); err == nil {
			v2 := v
			input.Page = &v2
		} else {
			return err
		}
	}
	if val := request.GetQuery("size"); val != "" {
		if v, err := IntFromParam(val); err == nil {
			v2 := v
			input.Size = &v2
		} else {
			return err
		}
	}
	return nil
}

// handleCreateEvent 封装了端点的自动化执行流
func (e *ScalarDemoExecutor[T, C]) handleCreateEvent(request C, info MethodInfo) {
	native := request.Native()
	var input CreateEventInput
	if err := e.bindCreateEvent(request, &input); err != nil {
		request.RenderJson(e.r.ErrorToStatus(native, err), e.r.BindResData(native, nil, err))
		return
	}
	if err := e.validateCreateEvent(native, &input); err != nil {
		request.RenderJson(e.r.ErrorToStatus(native, err), e.r.BindResData(native, nil, err))
		return
	}
	result, err := e.biz.CreateEvent(request.Context(), &input)
	if err != nil {
		request.RenderJson(e.r.ErrorToStatus(native, err), e.r.BindResData(native, nil, err))
		return
	}
	dtoResult, dErr := result.ToDTO(native)
	if dErr != nil {
		request.RenderJson(e.r.ErrorToStatus(native, dErr), e.r.BindResData(native, nil, dErr))
		return
	}
	request.RenderJson(201, e.r.BindResData(native, dtoResult, nil))
}

// bindCreateEvent 自动生成的参数提取与转换实现
func (e *ScalarDemoExecutor[T, C]) bindCreateEvent(request C, input *CreateEventInput) error {
	var dto CreateEventInputDTO
	if err := request.Payload(SourceJson, &dto); err != nil {
		return err
	}
	if err := input.FromDTO(request.Native(), &dto); err != nil {
		return err
	}
	return nil
}

// validateCreateEvent 参数验证逻辑
func (e *ScalarDemoExecutor[T, C]) validateCreateEvent(ctx T, input *CreateEventInput) error {
	// Pass 1: Required validations
	if err := e.v.Required(ctx, "name", input.Name); err != nil {
		return err
	}
	if err := e.v.Required(ctx, "startTime", input.StartTime); err != nil {
		return err
	}
	if err := e.v.Required(ctx, "endTime", input.EndTime); err != nil {
		return err
	}

	// Pass 2: Other validations
	return nil
}
